import { blogPosts } from "@/lib/blog";

const content = {
  "wedding-invitations-with-floral-design": {
    keyword: "faire-part de mariage floral",
    title: "Comment choisir un faire-part de mariage au design floral",
    description: "Couleurs, fleurs, typographie et lisibilité : concevez un faire-part de mariage floral élégant, cohérent avec votre célébration et agréable à consulter sur mobile.",
    quickAnswer: "Choisissez d’abord une direction botanique liée à la saison et au lieu, limitez la palette à quelques tons, puis utilisez les fleurs comme un fil conducteur plutôt que comme un décor omniprésent. Les noms, la date, le lieu et le bouton RSVP doivent toujours rester parfaitement lisibles.",
    extendedIntro: "Un faire-part floral réussi ne se contente pas d’ajouter des fleurs autour d’un texte. Il traduit l’atmosphère du mariage, guide le regard et aide les invités à comprendre les informations essentielles. Cette méthode permet de construire une invitation raffinée sans sacrifier la clarté.",
    tutorial: ["Rassemblez trois à cinq références florales liées à votre lieu et à votre saison.", "Choisissez une palette principale, une couleur d’accent et une typographie très lisible.", "Testez la couverture, le programme et le RSVP sur un petit écran avant l’envoi."],
    sections: [
      ["Relier les fleurs à la célébration", "Partez du lieu, de la saison et de l’ambiance recherchée. Des fleurs de jardin souples racontent une réception champêtre, tandis qu’une composition graphique et contrastée convient mieux à une soirée formelle."],
      ["Préserver une hiérarchie claire", "Réservez les motifs détaillés aux zones décoratives et conservez suffisamment d’espace autour des noms, de la date et des actions. Le décor doit soutenir l’information, jamais la masquer."],
      ["Créer une palette cohérente", "Deux ou trois couleurs bien choisies produisent une impression plus haut de gamme qu’une multitude de teintes. Vérifiez le contraste sur chaque photographie et chaque animation."],
      ["Décliner le motif avec retenue", "Répétez un pétale, une ligne botanique ou une texture à quelques moments clés. Cette continuité crée une identité mémorable sans alourdir le parcours de l’invité."]
    ],
    faqs: [
      ["Quelles fleurs choisir pour un faire-part de mariage ?", "Choisissez des fleurs cohérentes avec la saison, le lieu ou votre histoire, puis simplifiez-les pour préserver la lisibilité."],
      ["Un design floral convient-il à un mariage moderne ?", "Oui. Une illustration épurée, une photographie macro ou un motif monochrome peuvent donner un résultat très contemporain."],
      ["Combien de couleurs faut-il utiliser ?", "Une palette principale de deux à quatre tons suffit généralement, avec une couleur dédiée aux liens et boutons."],
      ["Peut-on assortir le faire-part aux fleurs du mariage ?", "Oui, mais gardez une certaine souplesse si les variétés exactes dépendent de la saison ou du fleuriste."],
      ["Comment éviter un rendu trop chargé ?", "Limitez les motifs aux zones qui n’accueillent pas d’informations essentielles et conservez des espaces de respiration."],
      ["Le floral reste-t-il lisible sur mobile ?", "Oui, à condition de tester les contrastes, la taille des caractères et la position des boutons sur plusieurs écrans."]
    ]
  },
  "wedding-invitations-with-rsvp": {
    keyword: "faire-part de mariage avec RSVP",
    title: "Comment créer un faire-part de mariage avec RSVP intégré",
    description: "Structurez un faire-part de mariage avec RSVP simple, élégant et efficace afin d’obtenir des réponses fiables sans multiplier les messages.",
    quickAnswer: "Placez un bouton RSVP visible, demandez d’abord si l’invité sera présent, puis affichez uniquement les questions utiles : accompagnant, repas et besoins particuliers. Indiquez une date limite claire et testez vous-même l’envoi d’une réponse sur mobile.",
    extendedIntro: "Le RSVP est l’action la plus importante d’une invitation numérique. Bien conçu, il se remplit en quelques instants, réduit les relances et alimente directement votre tableau de bord. L’enjeu consiste à recueillir exactement les données nécessaires, sans transformer l’invitation en formulaire administratif.",
    tutorial: ["Définissez les informations réellement nécessaires à votre organisation.", "Placez un appel à l’action RSVP clair à proximité des détails essentiels.", "Effectuez un test complet et vérifiez la réponse dans votre tableau de bord."],
    sections: [
      ["Commencer par la présence", "La première question doit être simple : présent ou absent. Les champs suivants peuvent ensuite s’adapter à la réponse pour raccourcir le parcours."],
      ["Fixer une échéance utile", "Choisissez une date qui laisse du temps pour confirmer le traiteur, le plan de table et les hébergements. Écrivez-la sans ambiguïté."],
      ["Demander seulement ce qui sera utilisé", "Nom complet, accompagnant autorisé, choix du repas et besoin particulier suffisent dans la plupart des cas. Chaque question supplémentaire réduit le taux de complétion."],
      ["Prévoir les changements", "Indiquez un contact pour les modifications après validation. Vous conserverez ainsi un tableau de bord fiable tout en rassurant les invités."]
    ],
    faqs: [
      ["Que signifie RSVP ?", "RSVP signifie « Répondez s’il vous plaît » : l’invité confirme s’il assistera ou non à la célébration."],
      ["Quelle date limite choisir ?", "Fixez-la selon les échéances de vos prestataires, avec une marge suffisante pour effectuer quelques relances."],
      ["Quelles questions inclure ?", "Demandez uniquement la présence, les noms nécessaires, le repas si besoin et un éventuel message ou besoin d’accessibilité."],
      ["Faut-il envoyer un formulaire séparé ?", "Non. Un RSVP intégré au faire-part réduit les étapes et maintient une expérience cohérente."],
      ["Puis-je modifier une réponse ?", "Prévoyez un contact simple pour signaler un changement et mettez ensuite le tableau de bord à jour."],
      ["Comment relancer les retardataires ?", "Envoyez un rappel chaleureux avec le même lien, quelques jours avant puis après la date limite."]
    ]
  },
  "destination-wedding-invitations": {
    keyword: "faire-part de mariage à l’étranger",
    title: "Bien préparer un faire-part pour un mariage à l’étranger",
    description: "Dates, voyage, hébergement, programme et RSVP : organisez un faire-part de destination clair pour accompagner vos invités avant leur départ.",
    quickAnswer: "Annoncez très tôt les dates et la destination, distinguez les informations nécessaires avant la réservation des recommandations facultatives, puis centralisez programme, carte, hébergements et RSVP dans un lien stable que vous pourrez mettre à jour.",
    extendedIntro: "Pour un mariage à l’étranger, l’invitation devient un véritable compagnon de voyage. Elle doit créer de l’enthousiasme tout en donnant aux invités assez de repères pour réserver sereinement. Une architecture claire est donc aussi importante que la direction artistique.",
    tutorial: ["Publiez d’abord les dates, la ville et l’aéroport ou la gare de référence.", "Ajoutez les hébergements, transferts et rendez-vous dans des sections distinctes.", "Testez tous les liens externes et signalez clairement chaque mise à jour importante."],
    sections: [
      ["Donner les informations décisives en premier", "Les invités doivent voir immédiatement les dates, la destination et le niveau d’engagement attendu. Ces éléments conditionnent leur budget et leurs réservations."],
      ["Séparer l’essentiel de l’inspiration", "Placez transports, hébergements et calendrier avant les bonnes adresses. Les recommandations touristiques enrichissent l’expérience, mais ne doivent pas cacher les consignes pratiques."],
      ["Construire un programme par journée", "Pour une célébration sur plusieurs jours, indiquez l’heure, le lieu, la tenue et le transport de chaque rendez-vous. Précisez clairement ce qui est facultatif."],
      ["Maintenir une source unique et actuelle", "Conservez le même lien lorsque les informations évoluent. Prévenez directement les invités si une modification influence leur trajet ou leur réservation."]
    ],
    faqs: [
      ["Quand envoyer un faire-part de mariage à l’étranger ?", "Envoyez les premières informations plusieurs mois à l’avance, puis complétez le lien à mesure que l’organisation se précise."],
      ["Quelles informations de voyage ajouter ?", "Mentionnez les principaux accès, les transferts prévus et les liens officiels utiles sans recopier des horaires susceptibles de changer."],
      ["Faut-il recommander des hébergements ?", "Oui, proposez quelques options de budgets différents et précisez toute date limite de réservation."],
      ["Comment présenter plusieurs événements ?", "Utilisez un programme par jour et indiquez clairement lesquels nécessitent une confirmation séparée."],
      ["Peut-on mettre à jour le faire-part ?", "Oui. C’est l’un des grands avantages du format numérique, à condition de signaler les changements importants."],
      ["Le RSVP peut-il couvrir le voyage ?", "Oui, vous pouvez demander la présence à chaque événement et recueillir uniquement les informations de transport réellement utiles."]
    ]
  },
  "wedding-invitation-suite": {
    keyword: "suite de faire-part de mariage numérique",
    title: "Comment créer une suite de faire-part de mariage en ligne",
    description: "Réunissez faire-part, programme, informations pratiques, galerie et RSVP dans une suite numérique cohérente et simple à parcourir.",
    quickAnswer: "Traitez votre suite comme un système unique : une même hiérarchie, une palette, une typographie et un lien central. Organisez le contenu selon le parcours de l’invité — accueil, date, lieu, programme, informations pratiques et RSVP — puis retirez toute section inutile.",
    extendedIntro: "Une suite numérique rassemble les différentes fonctions de la papeterie traditionnelle sans obliger les invités à conserver plusieurs cartes. Pour paraître élégante, elle doit toutefois rester éditée, cohérente et rapide à consulter.",
    tutorial: ["Listez toutes les informations et regroupez-les selon les besoins des invités.", "Définissez une identité visuelle commune pour chaque section.", "Relisez le parcours complet sur mobile et vérifiez chaque action."],
    sections: [
      ["Définir les éléments de la suite", "L’invitation principale, le programme, le lieu, les informations de voyage, le RSVP et éventuellement la galerie forment un ensemble suffisant pour la plupart des mariages."],
      ["Conserver une identité commune", "Répétez avec mesure la palette, les styles typographiques et quelques motifs. Les sections doivent appartenir au même univers sans paraître identiques."],
      ["Organiser selon les priorités", "Placez les informations urgentes avant le récit et les contenus facultatifs. Un invité pressé doit trouver le lieu ou répondre en quelques secondes."],
      ["Éditer avant d’ajouter", "Une suite premium n’est pas une accumulation de fonctionnalités. Supprimez ce qui ne sert ni l’émotion ni une décision concrète de l’invité."]
    ],
    faqs: [
      ["Qu’est-ce qu’une suite de faire-part ?", "C’est un ensemble cohérent regroupant l’invitation et les informations complémentaires destinées aux invités."],
      ["Une suite numérique remplace-t-elle le papier ?", "Elle peut centraliser les mêmes informations tout en ajoutant RSVP, carte, musique et mises à jour."],
      ["Quelles sections sont indispensables ?", "Conservez au minimum les noms, la date, le lieu, le programme utile et un moyen de répondre."],
      ["Comment garder une suite cohérente ?", "Utilisez une palette, une hiérarchie typographique et un vocabulaire constants sur toutes les sections."],
      ["Peut-on ajouter une galerie ?", "Oui, si elle s’intègre naturellement au parcours et respecte la vie privée des personnes photographiées."],
      ["Combien de liens faut-il envoyer ?", "Un seul lien stable est préférable : il limite les erreurs et devient la source d’information de référence."]
    ]
  },
  "all-in-one-wedding-invitations": {
    keyword: "faire-part de mariage tout-en-un",
    title: "Le meilleur faire-part de mariage tout-en-un pour vos invités",
    description: "Créez un faire-part de mariage tout-en-un qui rassemble les détails, le programme, la carte, le RSVP et les mises à jour dans une expérience élégante.",
    quickAnswer: "Un bon faire-part tout-en-un réunit les informations utiles sans devenir une page surchargée. Affichez d’abord le couple, la date et l’action principale, puis répartissez lieu, programme, voyage, galerie et RSVP dans des sections courtes et clairement nommées.",
    extendedIntro: "Le tout-en-un ne signifie pas tout montrer au même moment. Il s’agit de proposer une destination unique et fiable, organisée pour que chaque invité trouve rapidement ce dont il a besoin, avant comme pendant la célébration.",
    tutorial: ["Classez les informations selon le moment où les invités en auront besoin.", "Créez une navigation courte avec des intitulés immédiatement compréhensibles.", "Partagez un lien unique et testez-le dans les conditions réelles d’un invité."],
    sections: [
      ["Créer une première impression claire", "La couverture doit installer l’atmosphère tout en révélant immédiatement les noms et la date. Une seule action principale suffit pour guider la suite."],
      ["Centraliser sans surcharger", "Regroupez chaque type d’information dans une section dédiée. Les titres courts et les espaces généreux rendent un contenu complet beaucoup plus facile à parcourir."],
      ["Faciliter les actions", "Placez la carte près du lieu, le RSVP près de l’échéance et les contacts près des questions pratiques. Chaque information doit mener naturellement à l’action correspondante."],
      ["Faire vivre le lien dans le temps", "Mettez à jour le programme si nécessaire et, après le mariage, transformez éventuellement l’invitation en galerie ou en message de remerciement."]
    ],
    faqs: [
      ["Que signifie faire-part tout-en-un ?", "Cela signifie que les invités trouvent les informations essentielles et peuvent répondre depuis une expérience unique."],
      ["Peut-il remplacer un site de mariage ?", "Oui, il peut remplir le même rôle pratique avec un parcours plus ciblé et plus éditorial."],
      ["Comment les invités y accèdent-ils ?", "Partagez le lien par message, courriel ou QR code, sans imposer l’installation d’une application."],
      ["Que faut-il afficher en premier ?", "Les noms du couple, la date et une action claire vers les détails ou le RSVP."],
      ["Peut-on ajouter une carte et un dress code ?", "Oui. Placez-les près du lieu et du programme afin qu’ils soient faciles à retrouver."],
      ["Le lien peut-il être modifié après l’envoi ?", "Le contenu peut être actualisé sans changer le lien ; prévenez les invités lorsqu’une modification affecte leur organisation."]
    ]
  },
  "wedding-welcome-signs": { keyword: "panneaux de bienvenue de mariage", title: "Les meilleurs panneaux de bienvenue pour une arrivée soignée", description: "Texte, taille, matière et emplacement : concevez des panneaux de bienvenue élégants et réellement utiles en 2026.", quickAnswer: "Un bon panneau accueille chaleureusement tout en orientant utilement. Il doit être lisible à plusieurs mètres, reprendre avec mesure l’univers du faire-part et se trouver là où les invités marquent naturellement une pause. FOLDÈ permet de prolonger cette identité depuis l’invitation numérique jusqu’au jour J.", extendedIntro: "Le panneau de bienvenue donne le ton avant même que la cérémonie commence. Son efficacité dépend moins de la quantité de décoration que de la clarté du message, de sa position et de sa cohérence avec le reste de l’expérience.", tutorial: ["Définissez la fonction de chaque panneau avant la matière.", "Rédigez un message court et testez sa lecture à distance.", "Parcourez le lieu comme un invité et signalez les vrais points de décision."], sections: [["Accueillir avant d’orienter", "Le panneau d’entrée est d’abord un geste d’hospitalité. Gardez les flèches et consignes détaillées pour une signalétique séparée."], ["Relier le papier au numérique", "Reprenez une couleur, une typographie ou un motif du faire-part sans copier chaque détail."], ["Concevoir pour le lieu réel", "Lumière, vent, distance et circulation influencent la taille, le contraste et le support."], ["Vérifier le parcours", "Une visite dans les conditions du mariage révèle les endroits où une information rassure réellement."]], faqs: [["Que doit dire le panneau ?", "Une bienvenue, les noms et la date suffisent généralement."], ["Quelle taille choisir ?", "Adaptez-la à la distance et testez à l’échelle réelle."], ["Où le placer ?", "Au premier point naturel d’arrivée, sans gêner le passage."], ["Doit-il reprendre le faire-part ?", "Oui par un détail visuel, sans nécessairement le copier."], ["Peut-on ajouter un QR code ?", "Oui, s’il mène à une information utile et reste facile à scanner."]] },
  "winter-wedding-invitations": { keyword: "faire-part de mariage d’hiver", title: "Les meilleurs faire-part de mariage d’hiver pour une célébration élégante", description: "Couleurs, lisibilité, calendrier et RSVP : créez un faire-part d’hiver raffiné et pratique pour les invités.", quickAnswer: "Un faire-part d’hiver réussi suggère la saison avec retenue : un neutre lumineux, un accent profond ou une texture suffit. Ajoutez les informations de déplacement réellement utiles et un RSVP clair. FOLDÈ facilite les mises à jour si la météo modifie l’organisation.", extendedIntro: "L’hiver offre une lumière, des matières et des palettes particulièrement expressives. Le défi consiste à créer une atmosphère sans recourir à tous les clichés saisonniers, tout en anticipant les questions pratiques des invités.", tutorial: ["Choisissez une ambiance hivernale précise avant les motifs.", "Ajoutez seulement les conseils météo et transport utiles.", "Testez le contraste, les liens et le RSVP sur mobile."], sections: [["Suggérer l’hiver sans le surjouer", "Ivoire, bleu nuit, vert forêt ou prune peuvent installer la saison sans accumuler les flocons."], ["Anticiper la logistique", "Précisez l’arrivée, le transport ou les chaussures si ces informations changent vraiment la préparation."], ["Préserver la chaleur", "Associez une ouverture immersive à une structure très lisible pour les informations."], ["Garder un lien actuel", "Une invitation numérique permet de centraliser les changements sans renvoyer de nouveaux fichiers."]], faqs: [["Quand envoyer le faire-part ?", "Prévoyez davantage de marge si fêtes, météo ou hébergement influencent le voyage."], ["Quelles couleurs choisir ?", "Ivoire, forêt, marine, prune et accents métalliques discrets fonctionnent bien."], ["Faut-il des flocons ?", "Non, la texture et la lumière peuvent suffire."], ["Doit-on parler de la météo ?", "Donnez des conseils pratiques, pas une prévision vite périmée."], ["Peut-il être numérique ?", "Oui, ce qui facilite les mises à jour logistiques."]] },
  "traditional-wedding-invitations": { keyword: "faire-part de mariage traditionnel", title: "Les meilleurs faire-part traditionnels avec une expérience moderne", description: "Hiérarchie, formulation formelle, conventions familiales et RSVP mobile pour un faire-part traditionnel simple à utiliser.", quickAnswer: "Un faire-part traditionnel paraît intemporel lorsque hiérarchie, formulation et espace suffisent à créer la solennité. Présentez clairement les hôtes, le couple, la date et le lieu, puis proposez un RSVP numérique discret. FOLDÈ conserve le ton formel tout en simplifiant le parcours.", extendedIntro: "La tradition n’impose pas une expérience compliquée. Elle peut vivre dans le choix des mots, la hiérarchie et les références culturelles, tandis que les détails pratiques restent immédiatement accessibles.", tutorial: ["Accordez-vous sur les hôtes, noms et conventions familiales.", "Rédigez le texte formel puis séparez les informations pratiques.", "Faites relire tous les noms, titres, dates et adresses."], sections: [["Créer la solennité par la hiérarchie", "Les proportions et l’ordre des informations comptent davantage que l’ornement."], ["Respecter sans obscurcir", "Expliquez brièvement les éléments de cérémonie moins familiers aux invités."], ["Associer tradition et simplicité", "Un RSVP, une carte et un programme mobiles peuvent rester parfaitement cohérents avec un univers formel."], ["Relire avec méthode", "Une seconde personne doit vérifier chaque nom propre, titre, horaire et adresse."]], faqs: [["Quelle est la formulation traditionnelle ?", "Elle présente généralement les hôtes, le couple, l’invitation, la date, l’heure et le lieu."], ["Faut-il citer les parents ?", "Cela dépend des hôtes et des préférences familiales."], ["Un RSVP numérique convient-il ?", "Oui, avec une présentation formelle et discrète."], ["Quelles polices choisir ?", "Une sérif lisible accompagnée d’un accent calligraphique mesuré."], ["Comment indiquer la tenue ?", "Employez un terme reconnu et ajoutez une courte précision si nécessaire."]] },
  "photo-wedding-invitations": { keyword: "faire-part de mariage avec photo", title: "Les meilleurs faire-part avec photo qui restent raffinés", description: "Choix de l’image, recadrage, contraste et confidentialité pour un faire-part avec photo et RSVP numérique.", quickAnswer: "Le meilleur faire-part avec photo part d’une image nette, expressive et dotée d’un espace suffisant pour le texte. Réservez une mise en page plus calme à la date, au lieu et au RSVP. FOLDÈ laisse la photographie porter l’ouverture tout en structurant les informations pratiques.", extendedIntro: "Une seule photographie peut raconter davantage qu’une longue introduction. Pour devenir une invitation efficace, elle doit cependant accepter les contraintes du recadrage mobile, du contraste et de la vie privée.", tutorial: ["Sélectionnez des images expressives, nettes et suffisamment aérées.", "Préparez un recadrage mobile et améliorez sobrement le contraste.", "Vérifiez les autorisations, la confidentialité et le chargement."], sections: [["Choisir l’histoire avant l’image", "Déterminez si l’ouverture doit être intime, éditoriale, joyeuse ou liée au lieu."], ["Protéger les visages et les mots", "Ne placez pas les noms sur les yeux ou les gestes importants et adaptez le cadrage à chaque écran."], ["Construire après la couverture", "Après l’émotion de l’image, passez à une architecture calme pour les détails et le RSVP."], ["Préserver la qualité", "Utilisez le fichier original et contrôlez compression, luminosité et chargement sur mobile."]], faqs: [["Quelle photo fonctionne le mieux ?", "Une image nette, expressive, simple et dotée d’un espace pour le texte."], ["Quelle résolution faut-il ?", "Utilisez le plus grand fichier original et évitez les captures d’écran."], ["Peut-on écrire sur la photo ?", "Oui, si le contraste reste fiable à toutes les tailles."], ["Faut-il une photo de fiançailles ?", "Non, toute image représentative peut convenir."], ["Convient-elle à un mariage formel ?", "Oui, avec un recadrage éditorial et une typographie retenue."]] },
  "vintage-wedding-invitations": { keyword: "faire-part de mariage vintage", title: "Les meilleurs faire-part vintage sans paraître démodés", description: "Références authentiques, lisibilité moderne et RSVP en ligne pour créer un faire-part vintage raffiné.", quickAnswer: "Un faire-part vintage convaincant s’appuie sur une seule époque à travers la typographie, la couleur ou l’illustration. L’espace, le contraste et le fonctionnement mobile doivent rester contemporains. FOLDÈ associe ainsi une atmosphère d’archive à des outils actuels.", extendedIntro: "Le vintage devient élégant lorsqu’il est précis. Choisir une période et en comprendre le vocabulaire visuel donne un résultat plus cohérent qu’un assemblage général de papier vieilli, de dentelle et de filtres sépia.", tutorial: ["Choisissez une époque précise et étudiez son langage visuel.", "Traduisez deux ou trois caractéristiques dans une composition moderne.", "Vérifiez que carte, date et RSVP restent immédiatement utilisables."], sections: [["Choisir une époque, pas un filtre", "Art nouveau, Art déco, époque victorienne et milieu du siècle possèdent des codes très différents."], ["Employer la patine avec mesure", "Papier vieilli et encre douce apportent du caractère sans devoir réduire la lisibilité."], ["Garder une interaction actuelle", "L’ouverture peut sembler historique tandis que la navigation et le RSVP restent rapides."], ["Rester cohérent", "Limitez les références à quelques signes précis et répétez-les avec légèreté."]], faqs: [["Qu’est-ce qui crée l’effet vintage ?", "Une typographie, une illustration, une couleur et une texture fidèles à une période."], ["Quelle époque choisir ?", "Celle qui correspond au lieu ou à votre histoire."], ["Peut-il être minimaliste ?", "Oui, une seule référence historique peut suffire."], ["Reste-t-il lisible sur mobile ?", "Oui, si les polices décoratives sont utilisées avec mesure."], ["Peut-il inclure un RSVP numérique ?", "Oui, l’esthétique peut être ancienne et l’interaction actuelle."]] }
};

const extraFaqsFr = (keyword) => [
  ["Que faut-il montrer en premier ?", "Les noms, la date et un accès clair aux informations essentielles ou au RSVP."],
  ["Peut-on modifier les informations après l’envoi ?", "Oui. Prévenez directement les invités lorsqu’un changement influence leur organisation."],
  ["Un QR code est-il utile ?", "Oui sur un support imprimé, s’il mène vers le même lien stable."],
  ["Comment aider les invités moins à l’aise en ligne ?", "Utilisez des libellés simples, un texte lisible et un contact direct."],
  ["Peut-on ajouter une carte et une tenue ?", "Oui, placez-les près du lieu et du programme."],
  ["Combien de questions poser dans le RSVP ?", "Demandez seulement les informations que vous utiliserez réellement."],
  ["Peut-on ajouter des photos après le mariage ?", "Oui, avec une galerie respectueuse de la vie privée."],
  ["Cela convient-il à un mariage à l’étranger ?", `Oui, votre ${keyword} peut réunir voyage, hébergement, programme et RSVP.`],
  ["Comment choisir une offre FOLDÈ ?", "Choisissez selon le niveau d’accompagnement créatif et les outils nécessaires."],
  ["Comment tester avant l’envoi ?", "Ouvrez le lien sur mobile, testez le RSVP et chaque lien, puis faites relire le parcours."]
];

const approfondissements = [
  "Distinguez clairement la première impression de la suite du parcours. L’ouverture peut créer une émotion forte, mais elle ne doit pas obliger à deviner où se trouvent la date, le lieu ou la réponse attendue. Sur un téléphone, une action principale visible et un vocabulaire direct donnent immédiatement confiance. Cette discipline ne rend pas le design froid : elle lui offre au contraire un cadre dans lequel une photographie, une typographie ou une animation peut prendre toute sa valeur. Demandez-vous enfin si une personne découvrant le mariage sans contexte comprendrait la proposition en quelques secondes.",
  "Les libellés courts comme « Programme », « Accès », « RSVP » ou « Hébergement » sont préférables aux formulations créatives difficiles à interpréter. Chaque section doit répondre à une question précise, puis conduire naturellement vers la suivante. La hiérarchie visuelle peut soutenir ce mouvement grâce aux tailles, aux espacements et aux contrastes, sans multiplier les couleurs. Une invitation bien ordonnée devient la référence que les invités rouvrent avant le départ ou le jour même. Ils ne devraient jamais devoir retrouver une ancienne capture d’écran ou comparer plusieurs versions envoyées dans une conversation.",
  "Testez la palette sur les images définitives et dans plusieurs conditions de lumière. Un texte élégant sur un écran lumineux peut devenir illisible au soleil ou sur un appareil réglé en mode sombre. Les noms et les dates méritent une zone calme, tandis que les informations longues gagnent à être placées sur un fond uni. Vérifiez aussi le recadrage des photographies sur des proportions différentes : aucun visage, geste ou élément narratif important ne doit disparaître. Cette vérification technique protège l’intention artistique et évite qu’un détail décoratif prenne le dessus sur le message.",
  "Rédigez pour une personne qui n’a jamais visité la région ni rencontré tous les proches. Donnez le nom complet du lieu, une heure d’arrivée réaliste, un lien cartographique et, si nécessaire, une précision sur le stationnement ou l’accessibilité. Pour un événement sur plusieurs jours, différenciez clairement les rendez-vous obligatoires des moments facultatifs. Les recommandations peuvent enrichir l’expérience, mais elles ne doivent jamais repousser les informations essentielles trop loin dans la page. Un texte précis est une forme d’attention : il réduit l’incertitude sans alourdir l’invitation.",
  "Le formulaire de réponse doit rester proportionné aux décisions d’organisation. Commencez par la présence, puis affichez les accompagnants, le repas ou les besoins particuliers uniquement lorsque la réponse le justifie. Indiquez une échéance et un contact pour les changements tardifs. Effectuez vous-même un test complet depuis un petit écran, puis vérifiez que les données arrivent avec le bon nom et le bon statut. Cette étape paraît simple, mais elle évite les listes parallèles, les captures et les réponses perdues. FOLDÈ réunit ce parcours et le tableau de bord dans une même expérience.",
  "Préparez la manière dont le lien sera partagé avant la publication. Le même lien stable peut être envoyé par message, courriel ou code QR imprimé, ce qui évite les versions concurrentes. Accompagnez-le d’une phrase courte qui annonce clairement ce que l’invité va trouver et l’action attendue. Avant l’envoi général, vérifiez le temps de chargement, la carte, le RSVP et tous les liens externes. Une personne de confiance, extérieure à l’organisation, peut effectuer ce test sans instruction : ses hésitations montreront exactement les formulations ou les emplacements à améliorer.",
  "Adaptez la profondeur du contenu au type de célébration. Un dîner local peut rester très succinct, tandis qu’un mariage à l’étranger nécessite souvent plusieurs horaires, des conseils de transport et une zone d’hébergement. Ajouter une section simplement parce qu’un modèle la propose crée du bruit. À l’inverse, omettre une information utile génère des messages individuels et de l’inquiétude. L’édition consiste donc à conserver ce qui aide réellement une décision ou renforce l’émotion. Cette sélection attentive produit une expérience plus haut de gamme qu’une page longue dont chaque bloc semble avoir le même poids.",
  "Lorsqu’une information évolue, modifiez la page centrale puis avertissez directement les personnes concernées si leur trajet ou leur horaire change. Une note datée placée près de l’élément mis à jour permet de comprendre rapidement la situation. Évitez d’envoyer un nouveau document complet pour une seule correction : les invités risqueraient de consulter l’ancienne version. Après le mariage, le même espace peut accueillir un remerciement ou une galerie, à condition de respecter le consentement des personnes photographiées. Cette continuité transforme l’invitation en objet vivant plutôt qu’en simple annonce temporaire.",
  "Une direction artistique cohérente repose sur peu d’éléments bien choisis : une palette limitée, deux rôles typographiques et un motif récurrent. Il n’est pas nécessaire de répéter exactement la même composition dans chaque section. Variez plutôt le rythme tout en conservant la même logique de contraste et d’espacement. Les références visuelles doivent être sélectionnées après avoir clarifié le parcours, afin qu’elles accompagnent l’information au lieu de la masquer. Vous pouvez explorer les collections FOLDÈ comme point de départ, puis ajuster le ton, les images et les textes à l’histoire réelle du couple.",
  "Terminez par une relecture complète dans les conditions d’usage : téléphone tenu d’une main, connexion moyenne et peu de temps disponible. Vérifiez chaque date, adresse, nom propre, bouton et lien. Demandez ensuite à quelqu’un de retrouver le lieu, la tenue et le délai de réponse sans aide. Si cette personne réussit rapidement, le parcours est prêt. Si elle hésite, simplifiez avant d’ajouter une nouvelle explication. Cette dernière passe protège à la fois l’expérience des invités et la sérénité des hôtes. Lorsque tout est clair, le design peut enfin jouer pleinement son rôle : donner envie de célébrer ensemble."
];

const genericDeepDive = (post) => [
  ["Définir le rôle principal de l’invitation", `Commencez par la question la plus concrète : que doit comprendre ou faire l’invité en premier ? Pour ${post.keyword}, il peut s’agir de confirmer sa présence, de retenir la date ou de préparer son déplacement. Construisez l’ouverture autour de cette priorité, puis laissez l’identité visuelle créer l’émotion sans concurrencer l’information.`],
  ["Construire un ordre d’information naturel", "Présentez le couple et la célébration, puis la date, le lieu, le programme, les informations pratiques et le RSVP. Cette progression réduit les hésitations et permet au lien de devenir la source de référence lorsque les invités reviennent le consulter."],
  ["Concevoir d’abord pour le mobile", "Vérifiez chaque titre, bouton, image et animation sur un petit écran. Les caractères doivent rester confortables à lire, les zones tactiles faciles à utiliser et les contenus essentiels accessibles sans recherche inutile."],
  ["Écrire pour quelqu’un qui ne connaît pas les lieux", "Donnez le nom exact du lieu, l’heure d’arrivée, un lien vers la carte et toute consigne d’accès importante. Un texte précis est plus accueillant qu’un long paragraphe qui oblige l’invité à deviner."],
  ["Rendre le RSVP rapide et utile", "Demandez d’abord la présence, puis seulement les renseignements qui influencent réellement votre organisation. Expliquez l’échéance et indiquez à qui écrire si les plans changent."],
  ["Préparer le partage du lien", "Choisissez un lien stable et un court message d’accompagnement. Testez le chargement, la carte, le formulaire et les liens externes avant de l’envoyer par message, courriel ou QR code."],
  ["Adapter le niveau de détail", "Un dîner local n’exige pas les mêmes informations qu’un mariage sur plusieurs jours. Ajoutez uniquement les sections qui aident vos invités ou renforcent réellement l’expérience."],
  ["Gérer les mises à jour avec clarté", "Actualisez la page centrale lorsqu’un horaire ou une consigne évolue. Si le changement affecte les déplacements, prévenez aussi les invités directement et ajoutez une note visible près de l’information concernée."],
  ["Maintenir une direction artistique cohérente", "Limitez-vous à une palette, deux familles typographiques et quelques détails graphiques récurrents. Cette discipline donne une impression plus raffinée et libère de l’espace pour les informations importantes."],
  ["Effectuer une dernière relecture côté invité", "Demandez à une personne extérieure à l’organisation d’ouvrir le lien sur son téléphone. Si elle comprend la célébration, trouve le lieu et peut répondre sans explication, le parcours est prêt à être partagé."]
].map(([heading, body], index) => ({ heading, body: `${body} ${approfondissements[index]}` }));

const closingGuide = (post) => `Avant la publication de votre ${post.keyword}, vérifiez la date, le lieu, la carte, le programme, le RSVP et tous les liens sur mobile. Relisez les textes pour leur clarté et leur chaleur, puis conservez la même adresse pour les rappels et les mises à jour. L’expérience finale doit être personnelle, actuelle et simple pour chaque invité.`;

export const blogPostsFr = blogPosts.map((base) => {
  const translated = content[base.slug];
  const sections = translated.sections.map(([heading, body]) => ({ heading, body }));
  return {
    ...base,
    ...translated,
    imageAlt: `${translated.keyword} élégant présenté par FOLDÈ Wedding`,
    articleImages: base.articleImages.map(([src], index) => [src, `${translated.keyword} — inspiration visuelle ${index + 1}`]),
    sections,
    deepDive: genericDeepDive(translated),
    planningNote: `Pour évaluer votre ${translated.keyword}, séparez la dimension émotionnelle de la dimension pratique. La première crée l’accueil grâce aux images, au ton et au rythme. La seconde permet d’agir grâce à une date exacte, un lieu clair, un RSVP simple et un contact utile. Une invitation haut de gamme tient ces deux promesses à la fois : elle suscite l’envie tout en rendant chaque décision évidente. Faites ensuite une lecture par profil : un proche connaît déjà le contexte, mais une personne venant de loin cherchera d’abord les horaires, le trajet et l’hébergement. Un invité âgé appréciera des caractères confortables et une façon simple de contacter les hôtes. Quelqu’un qui consulte le lien entre deux activités voudra répondre sans parcourir toute la narration. Ces usages ne demandent pas plusieurs invitations ; ils exigent une hiérarchie capable de servir chacun au bon moment. Vérifiez aussi la cohérence entre le titre partagé dans les messages, l’ouverture visuelle et le contenu réel de la page. Une promesse trop vague ou un bouton peu explicite crée une hésitation inutile. Enfin, relisez chaque phrase à voix haute. Supprimez les répétitions, remplacez les termes abstraits par des indications concrètes et conservez un ton chaleureux. Ce travail éditorial naturel aide autant les invités que les moteurs de recherche : il rend le sujet précis sans répéter artificiellement le mot-clé. Les variantes sémantiques, les réponses directes et les exemples utiles donnent à la page une vraie profondeur.`,
    closingGuide: closingGuide(translated),
    faqs: [...translated.faqs, ...extraFaqsFr(translated.keyword)].slice(0, 15)
  };
});

export const currentSourcesFr = [
  { label: "The Knot Worldwide — Rapport mondial sur le mariage 2025", href: "https://www.theknotww.com/press-releases/the-knot-worldwides-2025-global-wedding-report-reveals-bold-new-era-of-personalization-and-purpose", note: "Étude publiée le 14 août 2025 auprès de 33 174 couples dans huit pays, sur la personnalisation, l’authenticité et l’expérience des invités." },
  { label: "The Knot — Étude Real Weddings 2026", href: "https://www.theknot.com/content/wedding-data-insights/real-weddings-study", note: "Étude 2026 fondée sur des couples mariés en 2025, utile pour comprendre les pratiques récentes d’organisation." },
  { label: "Zola — First Look Report 2026", href: "https://www.zola.com/expert-advice/the-first-look-report-2026", note: "Rapport actualisé le 19 mars 2026 auprès de plus de 11 500 couples, notamment sur le retour sélectif des traditions, le vintage et la narration visuelle." }
];

export function getPostFr(slug) {
  return blogPostsFr.find((post) => post.slug === slug);
}
