const fr = {
  'Scroll left': 'Faire défiler vers la gauche',
  'Scroll right': 'Faire défiler vers la droite',
  'Everything you need for an elegant, personalized invitation.': 'Tout ce qu’il faut pour une invitation élégante et personnalisée.',
  'Select from exclusive design universes': 'Choisissez parmi des univers graphiques exclusifs',
  'Personalized with your colors & details': 'Personnalisation avec vos couleurs et vos informations',
  'Interactive RSVP form': 'Formulaire RSVP interactif',
  'Real-time guest dashboard': 'Tableau de bord des invités en temps réel',
  'Unlimited guests included': 'Invités illimités inclus',
  'Guest directory & table planner': 'Répertoire des invités et plan de table',
  'No AI credits included': 'Aucun crédit IA inclus',
  'Select Standard': 'Choisir Standard',
  'Most Popular': 'Le plus choisi',
  'A self-service invitation dashboard with AI credits and priority support.': 'Un tableau de bord en libre-service, avec des crédits IA et une assistance prioritaire.',
  'Everything in Standard included': 'Tout le contenu de Standard',
  'Create up to 5 images and 5 music tracks with AI': 'Créez jusqu’à 5 images et 5 musiques avec l’IA',
  'Express 24h Dedicated Support': 'Assistance dédiée express sous 24 h',
  'Self-service dashboard + priority support': 'Tableau de bord en libre-service et assistance prioritaire',
  'Custom sections (boarding pass, RSVP)': 'Sections personnalisées (carte d’embarquement, RSVP)',
  'Unlimited revisions': 'Révisions illimitées',
  'Select Premium': 'Choisir Premium',
  'Custom': 'Expert',
  '100% bespoke "Fait main" questionnaire onboarding, team review & site validation.': 'Un accompagnement entièrement sur mesure : questionnaire personnalisé, relecture par l’équipe et validation du site.',
  '100% bespoke questionnaire onboarding': 'Questionnaire initial entièrement personnalisé',
  'Hand-crafted ("Fait main") art direction': 'Direction artistique conçue sur mesure',
  'Hand-crafted art direction': 'Direction artistique conçue sur mesure',
  'Custom Envelope, Hero video, Menu & Photos': 'Enveloppe, vidéo de couverture, menu et photos personnalisés',
  'Direct review & validation by our team': 'Relecture et validation directes par notre équipe',
  'Studio crafts and publishes your invitation after approval': 'Le studio crée et publie votre invitation après validation',
  'Personal concierge & priority support': 'Conciergerie personnelle et assistance prioritaire',
  'Everything included in Premium': 'Tout le contenu de Premium',
  'Everything in Premium': 'Tout le contenu de Premium',
  'Select Custom': 'Choisir Expert',
  'Optional Add-ons:': 'Options supplémentaires :',
  'Video Cover — €19 · Custom Music — €19 · Additional Language — €19 · Multi-group Management — €29': 'Couverture vidéo — 19 € · Musique personnalisée — 19 € · Langue supplémentaire — 19 € · Gestion multigroupe — 29 €',
  'Dashboard': 'Tableau de bord',
  'Your Private Wedding Dashboard': 'Votre tableau de bord de mariage privé',
  'Track every RSVP response, dietary preference, and guest status in real time — elegantly organized and always at hand.': 'Suivez en temps réel chaque réponse, préférence alimentaire et statut d’invité, dans une interface élégante toujours à portée de main.',
  'Attending': 'Présents', 'Declined': 'Absents',
  'Real-time RSVP response tracking': 'Suivi des réponses RSVP en temps réel',
  'Clear organization at a glance': 'Une organisation claire en un coup d’œil',
  'One-click data export': 'Export des données en un clic',
  'Seamless on mobile & desktop': 'Une expérience fluide sur mobile et ordinateur',
  'Pending': 'En attente',
  'Client Stories': 'Témoignages de couples',
  'Loved by Our Couples': 'Plébiscité par nos couples',
  'Read stories from couples who trusted us for their special day.': 'Découvrez les témoignages de couples qui nous ont confié ce moment si particulier.',
  'Studio Experience': 'L’expérience Studio',
  'Prefer to Personalize at Your Own Pace?': 'Vous préférez personnaliser à votre rythme ?',
  'The FOLDÈ Studio gives you complete creative control — input your details, select your collection, and craft your invitation seamlessly.': 'Le Studio FOLDÈ vous donne toute la liberté créative : saisissez vos informations, choisissez votre collection et composez votre invitation en toute simplicité.',
  'Guided preparation — details, schedule, RSVP, accommodations': 'Préparation guidée : informations, programme, RSVP et hébergements',
  'FOLDÈ Collections — select a visual direction from our gallery': 'Collections FOLDÈ : choisissez une direction artistique dans notre galerie',
  'RSVP tracking & dashboard — monitor confirmations in real time': 'Suivi RSVP et tableau de bord : consultez les réponses en temps réel',
  'At your own pace — update your content whenever you wish': 'À votre rythme : modifiez votre contenu quand vous le souhaitez',
  'Start Live Preview': 'Ouvrir l’aperçu',
  'Everything you need to know before getting started.': 'Tout ce qu’il faut savoir avant de commencer.',
  'Bring Your Invitation to Life': 'Donnez vie à votre invitation',
  'Bespoke digital creations starting at €49.90': 'Créations numériques sur mesure à partir de 49,90 €',
  'Design Your Invitation': 'Créer votre invitation',
  'Have Questions? Get in Touch': 'Une question ? Écrivez-nous',
  'Whether you are exploring options or ready to begin, our team is here to assist you.': 'Que vous compariez encore les possibilités ou soyez prêts à commencer, notre équipe est là pour vous accompagner.',
  'or': 'ou', 'Response within a few hours ✨': 'Réponse sous quelques heures ✨', 'Design your invitation →': 'Créez votre invitation →',
  'Dietary preferences at a glance': 'Préférences alimentaires en un coup d’œil',
  'Export your guest list anytime': 'Exportez votre liste d’invités à tout moment',
  'What Couples Say': 'Témoignages',
  'Loved by Couples Around the World': 'Plébiscité par des couples du monde entier',
  'Frequently Asked Questions': 'Questions fréquentes',
  'Everything You Need to Know': 'Tout ce que vous devez savoir',
  'Ready to Create Something Unforgettable?': 'Prêts à créer une invitation inoubliable ?',
  'Your love story deserves an extraordinary beginning.': 'Votre histoire d’amour mérite un début exceptionnel.',
  'Start Designing': 'Commencer la création',
  'Choose Your Formula': 'Choisissez votre formule',
  'Everything you need for a perfect digital invitation': 'Tout ce qu’il faut pour une invitation numérique parfaite',
  'No hidden fees, no subscriptions. A single payment for an elegant, interactive digital wedding invitation with dedicated guidance.': 'Aucuns frais cachés, aucun abonnement. Un paiement unique pour une invitation de mariage numérique, élégante et interactive, avec un accompagnement dédié.',
  'Choose from our +15 exclusive templates and receive a personalized digital wedding invitation.': 'Choisissez parmi plus de 15 modèles exclusifs et recevez une invitation de mariage numérique personnalisée.',
  'Choose 1 template from over 15 options': 'Choisissez un modèle parmi plus de 15 créations',
  'Your colors and info applied': 'Vos couleurs et vos informations intégrées',
  'RSVP + private dashboard': 'RSVP et tableau de bord privé',
  'All languages supported': 'Toutes les langues prises en charge',
  'Start with Standard': 'Choisir Standard',
  'Personalize your invitation yourself with everything in Standard, priority support, custom sections, and AI creation tools.': 'Personnalisez vous-même votre faire-part avec tout ce qui est inclus dans Standard, une assistance prioritaire, des sections sur mesure et des outils de création par IA.',
  'Start with Premium': 'Choisir Premium',
  'A hand-crafted bespoke experience with a dedicated creative brief, team review, and studio validation.': 'Une expérience artisanale et sur mesure, avec brief créatif dédié, relecture par l’équipe et validation du studio.',
  'Start with Expert': 'Choisir Expert',
  "What's Included": 'Ce qui est inclus',
  'Every Detail, Covered': 'Chaque détail est pris en charge',
  'Our Vision': 'Notre vision',
  'Your Invitation Should Be as Memorable as Your Day': 'Votre invitation doit être aussi mémorable que votre mariage',
  'We founded FOLDÈ Design with a simple conviction: a wedding invitation is more than logistics — it is the very first chapter of your celebration. It deserves beauty, intention, and soul.': 'Nous avons fondé FOLDÈ Design autour d’une conviction simple : une invitation de mariage est bien plus qu’un support pratique, c’est le premier chapitre de votre célébration. Elle mérite beauté, intention et émotion.',
  'Elegant champagne wedding invitation': 'Invitation de mariage élégante aux tons champagne',
  'Why We Exist': 'Pourquoi nous existons',
  'Born from a Desire to Elevate': 'Né du désir de sublimer chaque détail',
  'Traditional paper invitations are beautiful — but they often get lost, arrive late, or lack the interactive depth that modern celebrations demand. Mass-produced digital alternatives, meanwhile, feel impersonal and disposable.': 'Les invitations traditionnelles en papier sont magnifiques, mais elles peuvent se perdre, arriver tard ou manquer de l’interactivité attendue aujourd’hui. Les solutions numériques produites en série, elles, paraissent souvent impersonnelles et éphémères.',
  'FOLDÈ was born in the space between these two worlds. We combine the timeless elegance of classic stationery with the power and convenience of digital technology — creating immersive, interactive experiences that your guests will remember long after the last dance.': 'FOLDÈ est né entre ces deux univers. Nous associons l’élégance intemporelle de la papeterie classique à la souplesse du numérique pour créer une expérience immersive dont vos invités se souviendront bien après la dernière danse.',
  'Our Values': 'Nos valeurs',
  'The Principles That Guide Every Creation': 'Les principes qui guident chacune de nos créations',
  'Elegance Above All': 'L’élégance avant tout',
  'Every visual element, every animation, every typographic choice is deliberate. We believe that true luxury lies in the details — and we obsess over each one.': 'Chaque élément visuel, chaque animation et chaque choix typographique répond à une intention. Le véritable luxe se niche dans les détails, et nous les soignons tous.',
  'Personal, Not Automated': 'Personnel, jamais automatisé',
  'Your invitation is not generated by a template engine. It is crafted by our team, in dialogue with you. Every project is unique because every couple is unique.': 'Votre invitation n’est pas produite automatiquement. Notre équipe la façonne avec vous. Chaque projet est unique, parce que chaque couple l’est aussi.',
  'Sustainable by Nature': 'Naturellement responsable',
  'A fully digital invitation means zero paper waste, no printing, and no shipping emissions. Elegance and responsibility are not mutually exclusive — they enhance each other.': 'Une invitation entièrement numérique évite le gaspillage de papier, l’impression et les émissions liées au transport. Élégance et responsabilité ne s’opposent pas : elles se renforcent.',
  'Innovation with Soul': 'L’innovation avec une âme',
  'We harness cutting-edge web technologies — immersive animations, interactive RSVP, real-time dashboards — but always in service of emotion, never for spectacle alone.': 'Nous utilisons les technologies web les plus avancées — animations immersives, RSVP interactif, tableaux de bord en temps réel — toujours au service de l’émotion, jamais du seul effet.',
  'What Sets Us Apart': 'Ce qui nous distingue',
  'More Than a Link — An Experience': 'Bien plus qu’un lien : une expérience',
  'When your guests tap that link, they do not just see information. They experience an immersive unveiling — an elegant opening animation, curated music, and a journey through every detail of your celebration. From the ceremony schedule to accommodation suggestions, from the photo gallery to the RSVP — everything unfolds with intention.': 'Lorsque vos invités ouvrent le lien, ils ne consultent pas simplement des informations. Ils découvrent une mise en scène immersive : animation d’ouverture élégante, musique choisie et parcours à travers chaque détail de votre célébration. Du programme aux hébergements, de la galerie au RSVP, tout se dévoile avec intention.',
  'This is what makes a FOLDÈ invitation different. It is not a webpage. It is a moment.': 'Voilà ce qui rend une invitation FOLDÈ différente. Ce n’est pas une page web, c’est un moment.',
  'Couples Served': 'Couples accompagnés', '12,000+': '12 000+', 'Guests Invited': 'Invités conviés', 'Satisfaction Rate': 'Taux de satisfaction',
  'Our Commitment': 'Notre engagement', 'The FOLDÈ Promise': 'La promesse FOLDÈ',
  "Let's Create Something Beautiful Together": 'Créons ensemble quelque chose d’exceptionnel',
  'Your story deserves an invitation worthy of it.': 'Votre histoire mérite une invitation à sa hauteur.',
  'Order Now': 'Créer mon invitation', 'Explore Gallery': 'Explorer les collections',
  'Back': 'Retour', 'Explore Our Design Collections': 'Explorez nos collections',
  'Find the universe that matches your story. Every collection can be fully personalized.': 'Trouvez l’univers qui correspond à votre histoire. Chaque collection est entièrement personnalisable.'
};

export function translateFr(english) {
  return fr[english] || english;
}
