"use client";

import { useLayoutEffect, useRef } from "react";

// English stays authoritative in the product components. These rows localize the
// transactional and authenticated surfaces without changing stored wedding data.
const rows = [
  ["Chosen by 500+ happy couples", "Choisi par plus de 500 couples heureux", "Elegido por más de 500 parejas felices"],
  ["Live Personalization Preview", "Aperçu de personnalisation en direct", "Vista previa de personalización en directo"],
  ["Select your preferred envelope animation, background video, and details to preview your invitation live.", "Choisissez l’animation de l’enveloppe, la vidéo d’arrière-plan et vos informations pour prévisualiser votre faire-part en direct.", "Elige la animación del sobre, el vídeo de fondo y tus datos para previsualizar la invitación en directo."],
  ["“Our guests were captivated from the moment they opened it!”", "« Nos invités ont été émerveillés dès l’ouverture ! »", "«¡Nuestros invitados quedaron fascinados desde el momento en que la abrieron!»"],
  ["— Camille & Antoine", "— Camille et Antoine", "— Camille y Antoine"],
  ["Envelope Animation", "Animation de l’enveloppe", "Animación del sobre"],
  ["Scroll horizontally →", "Faites défiler horizontalement →", "Desliza horizontalmente →"],
  ["Hero Theme Video", "Vidéo d’ambiance principale", "Vídeo principal de ambiente"],
  ["The Couple", "Le couple", "La pareja"],
  ["First name", "Prénom", "Nombre"],
  ["Partner's name", "Prénom de votre partenaire", "Nombre de tu pareja"],
  ["Wedding Details", "Informations sur le mariage", "Datos de la boda"],
  ["Wedding date", "Date du mariage", "Fecha de la boda"],
  ["Venue", "Lieu", "Lugar"],
  ["(optional)", "(facultatif)", "(opcional)"],
  ["Live Invitation Preview", "Aperçu du faire-part en direct", "Vista previa de la invitación"],
  ["This interactive preview lets you see how your names and date look on your design.", "Cet aperçu interactif vous permet de voir vos prénoms et votre date sur le modèle choisi.", "Esta vista previa interactiva te permite ver cómo quedan vuestros nombres y la fecha en el diseño."],
  ["After completing payment, you will unlock full access to your private dashboard", "Après le paiement, vous accéderez à votre tableau de bord privé", "Después de completar el pago, tendrás acceso completo a tu panel privado"],
  ["to customize photos, videos, music, envelope animations, RSVPs, and all event details.", "pour personnaliser les photos, les vidéos, la musique, les animations d’enveloppe, les RSVP et tous les détails de l’événement.", "para personalizar fotos, vídeos, música, animaciones del sobre, confirmaciones de asistencia y todos los datos del evento."],
  ["Unlimited guests", "Invités illimités", "Invitados ilimitados"],
  ["RSVP included", "RSVP inclus", "Confirmación de asistencia incluida"],
  ["Live in 24h", "En ligne sous 24 h", "Online en 24 h"],
  ["Standard Package", "Formule Standard", "Plan Estándar"],
  ["Choose your package", "Choisissez votre formule", "Elige tu plan"],
  ["Select the level of service you need.", "Choisissez le niveau d’accompagnement dont vous avez besoin.", "Selecciona el nivel de servicio que necesitas."],
  ["Your plan", "Votre formule", "Tu plan"],
  ["Standard", "Standard", "Estándar"],
  ["Choose from our +15 exclusive templates and receive a personalized digital wedding invitation with your texts, photos and colours.", "Choisissez parmi plus de 15 modèles exclusifs et recevez un faire-part de mariage numérique personnalisé avec vos textes, photos et couleurs.", "Elige entre más de 15 plantillas exclusivas y recibe una invitación digital de boda personalizada con vuestros textos, fotos y colores."],
  ["Choose 1 template from over 15 options", "Choisissez 1 modèle parmi plus de 15 créations", "Elige 1 plantilla entre más de 15 opciones"],
  ["Your colors and info applied", "Vos couleurs et informations intégrées", "Aplicamos vuestros colores y datos"],
  ["RSVP + private dashboard", "RSVP + tableau de bord privé", "Confirmación de asistencia + panel privado"],
  ["Guest directory & table planner", "Liste des invités et plan de table", "Lista de invitados y organización de mesas"],
  ["No AI credits included", "Aucun crédit IA inclus", "No incluye créditos de IA"],
  ["All languages supported", "Toutes les langues disponibles", "Disponible en todos los idiomas"],
  ["Unlimited guests included", "Nombre d’invités illimité", "Invitados ilimitados incluidos"],
  ["Personalize your invitation yourself with priority support, custom sections, and AI creation tools included.", "Personnalisez vous-même votre faire-part avec une assistance prioritaire, des sections sur mesure et des outils de création par IA inclus.", "Personaliza tú mismo la invitación con asistencia prioritaria, secciones a medida y herramientas de creación con IA incluidas."],
  ["Everything in Standard included", "Tout ce qui est inclus dans Standard", "Todo lo incluido en Estándar"],
  ["Create up to 5 images with AI", "Créez jusqu’à 5 images avec l’IA", "Crea hasta 5 imágenes con IA"],
  ["Create up to 5 music tracks with AI", "Créez jusqu’à 5 musiques avec l’IA", "Crea hasta 5 pistas de música con IA"],
  ["Create up to 5 images and 5 music tracks with AI", "Créez jusqu’à 5 images et 5 musiques avec l’IA", "Crea hasta 5 imágenes y 5 pistas de música con IA"],
  ["AI creation tools not included", "Outils de création par IA non inclus", "Herramientas de creación con IA no incluidas"],
  ["A polished invitation, ready quickly", "Un faire-part soigné, prêt rapidement", "Una invitación cuidada, lista rápidamente"],
  ["More creative freedom, managed by you", "Plus de liberté créative, gérée par vous", "Más libertad creativa, gestionada por ti"],
  ["A unique design, created for you", "Une création unique, réalisée pour vous", "Un diseño único, creado para ti"],
  ["Express 24h Dedicated Support", "Assistance dédiée express sous 24 h", "Asistencia exclusiva exprés en 24 h"],
  ["Self-service dashboard + priority support", "Tableau de bord autonome + assistance prioritaire", "Panel autogestionable + asistencia prioritaria"],
  ["Custom sections (boarding pass, RSVP options)", "Sections personnalisées (carte d’embarquement, options RSVP)", "Secciones personalizadas (tarjeta de embarque, opciones de confirmación)"],
  ["Unlimited revisions", "Modifications illimitées", "Revisiones ilimitadas"],
  ["A bespoke hand-crafted experience with a dedicated creative brief, team review, and studio validation.", "Une expérience entièrement sur mesure avec brief créatif dédié, relecture par notre équipe et validation en studio.", "Una experiencia artesanal a medida con brief creativo, revisión del equipo y validación del estudio."],
  ["100% bespoke questionnaire onboarding", "Questionnaire de création 100 % sur mesure", "Cuestionario inicial 100 % personalizado"],
  ["Hand-crafted art direction", "Direction artistique réalisée à la main", "Dirección artística elaborada a mano"],
  ["Custom Envelope, Hero video, Menu & Photos", "Enveloppe, vidéo principale, menu et photos sur mesure", "Sobre, vídeo principal, menú y fotos personalizados"],
  ["Direct review & validation by our team", "Relecture et validation directes par notre équipe", "Revisión y validación directas de nuestro equipo"],
  ["Studio crafts and publishes your invitation after approval", "Le studio crée et publie votre faire-part après validation", "El estudio crea y publica vuestra invitación tras la aprobación"],
  ["Concierge priority support", "Assistance Conciergerie prioritaire", "Asistencia Concierge prioritaria"],
  ["Everything in Premium", "Tout ce qui est inclus dans Premium", "Todo lo incluido en Premium"],
  ["YOU'LL-LOVE-IT PROMISE", "NOTRE PROMESSE COUP DE CŒUR", "PROMESA TE VA A ENCANTAR"],
  ["We work with you, revision after revision, until your invitation moves you. You won't share it with the world until every detail feels exactly the way you dreamed it.", "Nous avançons avec vous, modification après modification, jusqu’à ce que votre faire-part vous émeuve. Vous ne le partagerez que lorsque chaque détail sera exactement comme vous l’aviez imaginé.", "Trabajamos con vosotros, revisión tras revisión, hasta que la invitación os emocione. No la compartiréis hasta que cada detalle sea exactamente como la habíais soñado."],
  ["I'll provide my own", "Je fournirai mon propre média", "Aportaré mi propio archivo"],
  ["Kissing Couple", "Couple qui s’embrasse", "Pareja besándose"],
  ["Sea View", "Vue sur mer", "Vistas al mar"],
  ["Palm Zoom", "Zoom sur les palmiers", "Zoom de palmeras"],
  ["Just Married Car", "Voiture des jeunes mariés", "Coche de recién casados"],
  ["Castle", "Château", "Castillo"],
  ["Royal Heritage", "Héritage royal", "Herencia real"],
  ["Sea Animation", "Animation marine", "Animación marina"],
  ["Seaview Balcony", "Balcon avec vue sur mer", "Balcón con vistas al mar"],
  ["Blush Ribbon", "Ruban rose poudré", "Lazo rosa empolvado"],
  ["Romantic Garden", "Jardin romantique", "Jardín romántico"],
  ["Luxury", "Luxe", "Lujo"],
  ["Royal Doves", "Colombes royales", "Palomas reales"],
  ["Imperial Light", "Lumière impériale", "Luz imperial"],
  ["Golden Palace", "Palais doré", "Palacio dorado"],
  ["Oriental Palace", "Palais oriental", "Palacio oriental"],
  ["Celestial Veil", "Voile céleste", "Velo celestial"],
  ["Ivory Veil", "Voile ivoire", "Velo marfil"],
  ["Rosé Veil", "Voile rosé", "Velo rosado"],
  ["Rose Bow", "Nœud rose", "Lazo rosa"],
  ["Majestic", "Majestueux", "Majestuoso"],
  ["Photo Scratch", "Photo à gratter", "Foto para rascar"],
  ["Pressed Love", "Amour pressé", "Amor prensado"],
  ["Big Entrance Gold Seal", "Grande entrée, sceau doré", "Gran entrada, sello dorado"],
  ["Velvet Garden", "Jardin de velours", "Jardín de terciopelo"],
  ["Como Villa", "Villa de Côme", "Villa de Como"],
  ["Teatro Curtain", "Rideau de théâtre", "Telón de teatro"],
  ["The Venue Estate", "Le domaine", "La finca"],
  ["Sweet Love", "Tendre amour", "Dulce amor"],
  ["Botanical Floral", "Floral botanique", "Floral botánico"],
  ["Big Entrance", "Grande entrée", "Gran entrada"],
  ["Processing Payment", "Paiement en cours", "Procesando el pago"],
  ["Please wait while we secure your order...", "Veuillez patienter pendant la sécurisation de votre commande…", "Espera mientras protegemos tu pedido…"],
  ["Almost there!", "Vous y êtes presque !", "¡Ya casi está!"],
  ["Enter your email to create your private dashboard and complete your order.", "Saisissez votre adresse e-mail pour créer votre tableau de bord privé et finaliser votre commande.", "Introduce tu correo electrónico para crear el panel privado y completar el pedido."],
  ["Email address", "Adresse e-mail", "Correo electrónico"],
  ["Already have an account?", "Vous avez déjà un compte ?", "¿Ya tienes una cuenta?"],
  ["Log in to your dashboard", "Se connecter au tableau de bord", "Inicia sesión en tu panel"],
  ["Secure payment", "Paiement sécurisé", "Pago seguro"],
  ["Instant confirmation", "Confirmation immédiate", "Confirmación inmediata"],
  ["Designer-made", "Créé par un designer", "Creado por diseñadores"],
  ["Pay", "Payer", "Pagar"],
  ["Payment Confirmed!", "Paiement confirmé !", "¡Pago confirmado!"],
  ["Contact Details", "Coordonnées", "Datos de contacto"],
  ["Now tell us about your wedding so we can start crafting your invitation.", "Parlez-nous maintenant de votre mariage afin que nous puissions commencer la création de votre faire-part.", "Cuéntanos ahora cómo será vuestra boda para que podamos empezar a crear la invitación."],
  ["Expert Creative Brief", "Brief créatif Expert", "Brief creativo Expert"],
  ["This exclusive brief is shared directly with our art direction team, so your invitation feels unmistakably yours.", "Ce brief exclusif est transmis directement à notre équipe de direction artistique afin de créer un faire-part qui vous ressemble vraiment.", "Este brief exclusivo se comparte directamente con nuestro equipo de dirección artística para crear una invitación inconfundiblemente vuestra."],
  ["Phone number (for WhatsApp or call)", "Numéro de téléphone (WhatsApp ou appel)", "Número de teléfono (WhatsApp o llamada)"],
  ["City / Country", "Ville / Pays", "Ciudad / País"],
  ["Guest count", "Nombre d’invités", "Número de invitados"],
  ["Envelope Choice", "Choix de l’enveloppe", "Selección del sobre"],
  ["Hero Video Choice", "Choix de la vidéo principale", "Selección del vídeo principal"],
  ["Languages", "Langues", "Idiomas"],
  ["Color preferences", "Préférences de couleurs", "Preferencias de color"],
  ["Invitation Sections", "Sections du faire-part", "Secciones de la invitación"],
  ["Select the sections you want", "Sélectionnez les sections souhaitées", "Selecciona las secciones que deseas"],
  ["Menu & Reception details", "Menu et détails de la réception", "Menú y datos de la recepción"],
  ["Photo Gallery", "Galerie photo", "Galería de fotos"],
  ["Your celebration story", "L’histoire de votre célébration", "La historia de vuestra celebración"],
  ["Inspiration links", "Liens d’inspiration", "Enlaces de inspiración"],
  ["Creative direction: must-haves and avoid", "Direction créative : indispensables et éléments à éviter", "Dirección creativa: imprescindibles y elementos que evitar"],
  ["Additional Details & Notes", "Informations et notes complémentaires", "Datos y notas adicionales"],
  ["Upload", "Importer", "Subir"],
  ["Your Bespoke Invitation is Being Crafted", "Votre faire-part sur mesure est en cours de création", "Estamos creando vuestra invitación a medida"],
  ["Estimated review & delivery:", "Délai estimé de relecture et de livraison :", "Revisión y entrega estimadas:"],
  ["3 Business Days", "3 jours ouvrés", "3 días laborables"],
  ["VIEW MY STUDIO SPACE →", "ACCÉDER À MON ESPACE STUDIO →", "IR A MI ESPACIO DE ESTUDIO →"],
  ["Back", "Retour", "Volver"],
  ["Continue", "Continuer", "Continuar"],
  ["Edit", "Modifier", "Editar"],
  ["Updating preview…", "Mise à jour de l’aperçu…", "Actualizando la vista previa…"],
  ["Your Name", "Votre prénom", "Tu nombre"],
  ["Partner's Name", "Prénom de votre partenaire", "Nombre de tu pareja"],
  ["Your Dream Venue", "Le lieu de vos rêves", "El lugar de vuestros sueños"],
  ["Ceremony", "Cérémonie", "Ceremonia"],
  ["Dinner", "Dîner", "Cena"],
  ["Party", "Soirée", "Fiesta"],
  ["Starter", "Entrée", "Entrante"],
  ["Main", "Plat principal", "Plato principal"],
  ["Sign In", "Connexion", "Iniciar sesión"],
  ["Sign Up", "Créer un compte", "Crear una cuenta"],
  ["Continue with Google", "Continuer avec Google", "Continuar con Google"],
  ["or with your email", "ou avec votre adresse e-mail", "o con tu correo electrónico"],
  ["Email Address", "Adresse e-mail", "Correo electrónico"],
  ["Password", "Mot de passe", "Contraseña"],
  ["Sending...", "Envoi en cours…", "Enviando…"],
  ["Don't have an account yet? Explore collections →", "Pas encore de compte ? Découvrir les collections →", "¿Aún no tienes una cuenta? Explora las colecciones →"],
  ["No active order", "Aucune commande active", "No hay ningún pedido activo"],
  ["Your personal wedding studio will become available once you choose a package and complete your order.", "Votre studio mariage personnel sera disponible après le choix d’une formule et la finalisation de votre commande.", "Tu estudio de boda personal estará disponible cuando elijas un plan y completes el pedido."],
  ["Signed in as", "Connecté avec", "Sesión iniciada como"],
  ["Explore packages →", "Découvrir les formules →", "Explorar los planes →"],
  ["Sign out", "Se déconnecter", "Cerrar sesión"],
  ["Your invitation is live!", "Votre faire-part est en ligne !", "¡Vuestra invitación ya está online!"],
  ["View my website →", "Voir mon site →", "Ver mi sitio →"],
  ["Copy link", "Copier le lien", "Copiar enlace"],
  ["Creation in Progress...", "Création en cours…", "Creación en curso…"],
  ["Estimated delivery:", "Livraison estimée :", "Entrega estimada:"],
  ["3 Days (72 hours)", "3 jours (72 heures)", "3 días (72 horas)"],
  ["PARIS STUDIO SUPPORT", "ASSISTANCE DU STUDIO PARISIEN", "ASISTENCIA DEL ESTUDIO DE PARÍS"],
  ["Request a Design Modification", "Demander une modification du design", "Solicitar un cambio de diseño"],
  ["Your plan includes", "Votre formule comprend", "Tu plan incluye"],
  ["2 full revision rounds", "2 cycles complets de modifications", "2 rondas completas de revisiones"],
  ["Sent to studio (folde.wedding@gmail.com) · Processing", "Envoyée au studio (folde.wedding@gmail.com) · En cours de traitement", "Enviada al estudio (folde.wedding@gmail.com) · En proceso"],
  ["Sending Request...", "Envoi de la demande…", "Enviando solicitud…"],
  ["EXPERT BENEFIT", "AVANTAGE EXPERT", "VENTAJA EXPERT"],
  ["AI Personalization Studio", "Studio de personnalisation IA", "Estudio de personalización con IA"],
  ["My Invitation", "Mon faire-part", "Mi invitación"],
  ["AI Studio", "Studio IA", "Estudio IA"],
  ["Guest List", "Liste des invités", "Lista de invitados"],
  ["RSVP Responses", "Réponses RSVP", "Confirmaciones de asistencia"],
  ["Table Management", "Plan de table", "Organización de mesas"],
  ["Share My Site", "Partager mon site", "Compartir mi sitio"],
  ["24/7 Customer Support", "Assistance client 24 h/24, 7 j/7", "Atención al cliente 24/7"],
  ["Your Wedding Space", "Votre espace mariage", "Vuestro espacio de boda"],
  ["Workspace", "Espace de travail", "Espacio de trabajo"],
  ["Log Out", "Se déconnecter", "Cerrar sesión"],
  ["Basic Details", "Informations principales", "Datos principales"],
  ["Partner 1 First Name", "Prénom de la première personne", "Nombre de la primera persona"],
  ["Partner 2 First Name", "Prénom de la seconde personne", "Nombre de la segunda persona"],
  ["Displayed Wedding Date", "Date de mariage affichée", "Fecha de boda mostrada"],
  ["Venue / Estate Name", "Nom du lieu ou du domaine", "Nombre del lugar o finca"],
  ["Reception Address (Live Address Assistance)", "Adresse de la réception (aide à la saisie)", "Dirección de la recepción (asistencia en directo)"],
  ["Website Sections & Visibility", "Sections et visibilité du site", "Secciones y visibilidad del sitio"],
  ["Interactive Location Map", "Carte interactive du lieu", "Mapa interactivo del lugar"],
  ["Schedule & Timeline", "Programme et déroulé", "Programa y horarios"],
  ["Wedding Menu", "Menu du mariage", "Menú de la boda"],
  ["Accommodations & Hotels", "Hébergements et hôtels", "Alojamiento y hoteles"],
  ["Dress Code", "Code vestimentaire", "Código de vestimenta"],
  ["Guest Photo Gallery", "Galerie photo des invités", "Galería de fotos de los invitados"],
  ["Memories (Slider)", "Souvenirs (carrousel)", "Recuerdos (carrusel)"],
  ["Envelope Design Template", "Modèle d’enveloppe", "Diseño del sobre"],
  ["Hero Design Template", "Modèle visuel principal", "Diseño visual principal"],
  ["Background Music", "Musique de fond", "Música de fondo"],
  ["Replay Envelope Opening", "Rejouer l’ouverture de l’enveloppe", "Repetir la apertura del sobre"],
  ["Live Preview Website", "Aperçu du site en direct", "Vista previa del sitio"],
  ["Publish Invite Site", "Publier le site du faire-part", "Publicar el sitio de la invitación"],
  ["Publishing...", "Publication…", "Publicando…"],
  ["Congratulations!", "Félicitations !", "¡Enhorabuena!"],
  ["Continue editing", "Continuer les modifications", "Seguir editando"],
  ["Guest Directory", "Liste des invités", "Directorio de invitados"],
  ["Manage your invitees and track who is attending your wedding.", "Gérez vos invités et suivez les confirmations de présence.", "Gestiona a los invitados y comprueba quién asistirá a la boda."],
  ["Add Guest", "Ajouter un invité", "Añadir invitado"],
  ["Add New Guest", "Ajouter un invité", "Añadir invitado"],
  ["Guest Full Name *", "Nom complet de l’invité *", "Nombre completo del invitado *"],
  ["Guest Name", "Nom de l’invité", "Nombre del invitado"],
  ["Bride's Guest", "Invité de la mariée", "Invitado de la novia"],
  ["Groom's Guest", "Invité du marié", "Invitado del novio"],
  ["Mutual Friends", "Amis communs", "Amigos en común"],
  ["All Sides", "Tous les groupes", "Todos los grupos"],
  ["All Statuses", "Tous les statuts", "Todos los estados"],
  ["Attending Only", "Présents uniquement", "Solo asistentes"],
  ["Declined Only", "Absents uniquement", "Solo ausentes"],
  ["Pending Response", "En attente de réponse", "Respuesta pendiente"],
  ["Attending", "Présent", "Asiste"],
  ["Declined", "Absent", "No asiste"],
  ["Pending", "En attente", "Pendiente"],
  ["Plus One", "Accompagnant", "Acompañante"],
  ["Meal", "Repas", "Menú"],
  ["Status", "Statut", "Estado"],
  ["Action", "Action", "Acción"],
  ["Delete", "Supprimer", "Eliminar"],
  ["Cancel", "Annuler", "Cancelar"],
  ["Submitted RSVPs", "RSVP reçus", "Confirmaciones recibidas"],
  ["All Responses", "Toutes les réponses", "Todas las respuestas"],
  ["Confirmed Attending", "Présences confirmées", "Asistencia confirmada"],
  ["Regretfully Declined", "Absences confirmées", "No asistirán"],
  ["Total Responses", "Nombre total de réponses", "Respuestas totales"],
  ["Meal Preference Breakdown", "Répartition des préférences de repas", "Resumen de preferencias de menú"],
  ["Table Seating Planner", "Plan de table", "Organizador de mesas"],
  ["Add Table", "Ajouter une table", "Añadir mesa"],
  ["Add New Table", "Ajouter une table", "Añadir mesa"],
  ["Table Name *", "Nom de la table *", "Nombre de la mesa *"],
  ["Capacity (Seats)", "Capacité (places)", "Capacidad (asientos)"],
  ["Create Table", "Créer la table", "Crear mesa"],
  ["Seated Guests", "Invités placés", "Invitados sentados"],
  ["Unassigned Guests", "Invités non placés", "Invitados sin mesa"],
  ["Assign to table...", "Attribuer une table…", "Asignar a una mesa…"],
  ["Share Your Wedding Site", "Partager votre site de mariage", "Comparte vuestro sitio de boda"],
  ["Invitation Link", "Lien du faire-part", "Enlace de la invitación"],
  ["Copy", "Copier", "Copiar"],
  ["Quick Share Options", "Options de partage rapide", "Opciones rápidas para compartir"],
  ["Email", "E-mail", "Correo electrónico"],
  ["Printable QR Code", "QR code à imprimer", "Código QR para imprimir"],
  ["Download QR Code PNG", "Télécharger le QR code en PNG", "Descargar código QR en PNG"],
  ["Need a hand?", "Besoin d’aide ?", "¿Necesitas ayuda?"],
  ["Support", "Assistance", "Asistencia"],
  ["Wedding Invitation Language", "Langue du faire-part de mariage", "Idioma de la invitación de boda"],
  ["Bespoke AI Studio", "Studio IA sur mesure", "Estudio de IA a medida"],
  ["AI Image Generator", "Générateur d’images IA", "Generador de imágenes IA"],
  ["AI Sound Generator", "Générateur de musique IA", "Generador de música IA"],
  ["Your Generated Illustrations", "Vos illustrations générées", "Tus ilustraciones generadas"],
  ["Your Generated Wedding Music", "Vos musiques de mariage générées", "Tu música de boda generada"],
  ["Illustration Description *", "Description de l’illustration *", "Descripción de la ilustración *"],
  ["Style or musical theme *", "Style ou thème musical *", "Estilo o tema musical *"],
  ["Reference Photo #1", "Photo de référence n° 1", "Foto de referencia n.º 1"],
  ["Reference Photo #2", "Photo de référence n° 2", "Foto de referencia n.º 2"],
  ["Select an illustration style", "Choisissez un style d’illustration", "Elige un estilo de ilustración"],
  ["Select a musical ambiance", "Choisissez une ambiance musicale", "Elige un ambiente musical"],
  ["Instrumental music only (no vocals)", "Musique instrumentale uniquement (sans voix)", "Solo música instrumental (sin voz)"],
  ["Ratio:", "Format :", "Formato:"],
  ["Active AI", "IA active", "IA activa"],
  ["Remove", "Retirer", "Quitar"],
  ["Both", "Les deux", "Ambos"],
  ["Bride", "Mariée", "Novia"],
  ["Groom", "Marié", "Novio"],
  ["Message", "Message", "Mensaje"],
  ["Response", "Réponse", "Respuesta"],
  ["Total Invited", "Total invités", "Total de invitados"],
  ["Attending Guests", "Invités présents", "Invitados asistentes"],
  ["Live Invite Link", "Lien du faire-part en ligne", "Enlace de la invitación online"],
  ["RSVP Deadline", "Date limite de réponse", "Fecha límite de confirmación"],
  ["Course (e.g., Starter)", "Service (ex. : entrée)", "Plato (p. ej., entrante)"],
  ["Dish Description", "Description du plat", "Descripción del plato"],
  ["Event Name (e.g., Ceremony)", "Nom de l’étape (ex. : cérémonie)", "Nombre del evento (p. ej., ceremonia)"],
  ["Time (e.g., 2:00 PM)", "Heure (ex. : 14 h 00)", "Hora (p. ej., 14:00)"],
  ["Hotel Name", "Nom de l’hôtel", "Nombre del hotel"],
  ["Rate / Info", "Tarif / Informations", "Tarifa / Información"],
  ["Delete guest", "Supprimer l’invité", "Eliminar invitado"],
  ["Delete table", "Supprimer la table", "Eliminar mesa"],
  ["Describe any text updates, photo changes, dress code tweaks, or timeline adjustments you would like us to make...", "Décrivez les modifications souhaitées pour les textes, les photos, le code vestimentaire ou le programme…", "Describe los cambios de texto, fotos, código de vestimenta u horarios que quieres que hagamos…"],
  ["Describe instruments, tempo, or desired mood...", "Décrivez les instruments, le tempo ou l’ambiance souhaitée…", "Describe los instrumentos, el tempo o el ambiente que deseas…"],
  ["Describe the desired illustration or style...", "Décrivez l’illustration ou le style souhaité…", "Describe la ilustración o el estilo que deseas…"],
  ["Search guest name...", "Rechercher un invité…", "Buscar invitado…"],
  ["Search guests...", "Rechercher des invités…", "Buscar invitados…"],
  ["Wedding Invitation QR Code", "QR code du faire-part de mariage", "Código QR de la invitación de boda"],
  ["Templates", "Modèles", "Plantillas"],
  ["Live Preview", "Aperçu en direct", "Vista previa en directo"],
  ["Scroll inside the phone to explore your invitation ↕", "Faites défiler l’écran du téléphone pour découvrir votre faire-part ↕", "Desplázate dentro del teléfono para explorar la invitación ↕"],
  ["Wedding Day", "Jour du mariage", "Día de la boda"],
  ["SAVE THE DATE", "RÉSERVEZ LA DATE", "RESERVA LA FECHA"],
  ["The Day Has Arrived!", "Le grand jour est arrivé !", "¡Ha llegado el gran día!"],
  ["We can't wait to celebrate with you", "Nous avons hâte de célébrer avec vous", "Estamos deseando celebrarlo con vosotros"],
  ["Scratch all three circles to discover the date", "Grattez les trois cercles pour découvrir la date", "Rasca los tres círculos para descubrir la fecha"],
  ["Reveal", "Révélation", "Descubrir"],
  ["Scratch to discover the date", "Grattez pour découvrir la date", "Rasca para descubrir la fecha"],
  ["Month", "Mois", "Mes"],
  ["Day", "Jour", "Día"],
  ["Year", "Année", "Año"],
  ["Save the date!", "Réservez la date !", "¡Reserva la fecha!"],
  ["Get directions", "Voir l’itinéraire", "Cómo llegar"],
  ["The Celebration", "La célébration", "La celebración"],
  ["Schedule", "Programme", "Programa"],
  ["What we have planned for you", "Ce que nous avons prévu pour vous", "Lo que hemos preparado para vosotros"],
  ["Where to stay during our celebration", "Où séjourner pendant notre célébration", "Dónde alojarse durante nuestra celebración"],
  ["A taste of what awaits you", "Un aperçu de ce qui vous attend", "Un adelanto de lo que os espera"],
  ["We hope to count on you", "Nous espérons pouvoir compter sur votre présence", "Esperamos poder contar con vosotros"],
  ["Please reply by March 30th, 2026", "Merci de répondre avant le 30 mars 2026", "Confirma tu asistencia antes del 30 de marzo de 2026"],
  ["First Name *", "Prénom *", "Nombre *"],
  ["First Name", "Prénom", "Nombre"],
  ["Last Name *", "Nom *", "Apellidos *"],
  ["Last Name", "Nom", "Apellidos"],
  ["Will you attend? *", "Serez-vous présent(e) ? *", "¿Asistirás? *"],
  ["Yes, with pleasure! 🎉", "Oui, avec plaisir ! 🎉", "¡Sí, con mucho gusto! 🎉"],
  ["Regretfully decline 🤍", "Non, à regret 🤍", "No podré asistir 🤍"],
  ["Will you be accompanied? *", "Serez-vous accompagné(e) ? *", "¿Vendrás acompañado/a? *"],
  ["I'm coming alone", "Je viendrai seul(e)", "Iré solo/a"],
  ["Yes, with a plus one", "Oui, avec un accompagnant", "Sí, con acompañante"],
  ["Yes, with family", "Oui, en famille", "Sí, con mi familia"],
  ["Allergies & Food Intolerances", "Allergies et intolérances alimentaires", "Alergias e intolerancias alimentarias"],
  ["SUBMIT RSVP", "ENVOYER MA RÉPONSE", "ENVIAR CONFIRMACIÓN"],
  ["Made with love by FOLDÈ Design", "Créé avec amour par FOLDÈ Design", "Creado con amor por FOLDÈ Design"],
  ["SPECIAL OFFER", "OFFRE SPÉCIALE", "OFERTA ESPECIAL"],
  ["CONTINUE TO PACKAGES →", "CHOISIR MA FORMULE →", "ELEGIR MI PLAN →"],
  ["CONTINUE TO PAYMENT →", "CONTINUER VERS LE PAIEMENT →", "CONTINUAR AL PAGO →"],
  ["PROCESSING...", "TRAITEMENT…", "PROCESANDO…"],
  ["PAY & START", "PAYER ET COMMENCER", "PAGAR Y EMPEZAR"],
  ["e.g. Sophie", "ex. : Sophie", "p. ej., Sofía"],
  ["e.g. Lucas", "ex. : Lucas", "p. ej., Lucas"],
  ["e.g. Château de Versailles", "ex. : Château de Versailles", "p. ej., Palacio de Versalles"],
  ["e.g. Paris, France", "ex. : Paris, France", "p. ej., París, Francia"],
  ["e.g. French, English", "ex. : français, anglais", "p. ej., español, inglés"],
  ["e.g. Blush pink, gold, ivory", "ex. : rose poudré, doré, ivoire", "p. ej., rosa empolvado, dorado, marfil"],
  ["e.g. 120", "ex. : 120", "p. ej., 120"],
  ["Payment error:", "Erreur de paiement :", "Error de pago:"],
  ["Please try again.", "Veuillez réessayer.", "Inténtalo de nuevo."],
  ["An error occurred. Please try again.", "Une erreur est survenue. Veuillez réessayer.", "Se ha producido un error. Inténtalo de nuevo."],
  ["YOUR NAME", "VOTRE PRÉNOM", "TU NOMBRE"],
  ["PARTNER'S NAME", "PRÉNOM DE VOTRE PARTENAIRE", "NOMBRE DE TU PAREJA"],
  ["✨ Save the date! ✨", "✨ Réservez la date ! ✨", "✨ ¡Reserva la fecha! ✨"],
  ["Please reply by", "Merci de répondre avant le", "Confirma tu asistencia antes del"],
  ["Will you attend?", "Serez-vous présent(e) ?", "¿Asistirás?"],
  ["Will you be accompanied?", "Serez-vous accompagné(e) ?", "¿Vendrás acompañado/a?"],
  ["e.g. None, Peanuts, Vegan...", "ex. : aucune, cacahuètes, régime végétalien…", "p. ej., ninguna, cacahuetes, dieta vegana…"],
  ["SPECIAL OFFER · You save $", "OFFRE SPÉCIALE · Vous économisez $", "OFERTA ESPECIAL · Ahorras $"],
  ["1 tap with", "Paiement express avec", "Pago exprés con"],
  ["Cisnes", "Cygnes", "Cisnes"],
  ["Bloom", "Floraison", "Floración"],
  ["Como Blue Seal", "Sceau bleu de Côme", "Sello azul de Como"],
  ["Tropical", "Tropical", "Tropical"],
  ["Soft Scratch", "Grattage délicat", "Rascado suave"],
  ["Bordeaux Horizon", "Horizon bordeaux", "Horizonte burdeos"],
  ["The Lace Edit", "L’Édition Dentelle", "La Edición de Encaje"],
  ["Le Jardin", "Le Jardin", "El Jardín"],
  ["Lace Photo Scratch", "Photo dentelle à gratter", "Foto de encaje para rascar"],
  ["Oasis Royale", "Oasis royale", "Oasis real"],
  ["MAY", "MAI", "MAYO"],
  ["March 30th, 2026", "30 mars 2026", "30 de marzo de 2026"],
  ["Cocktail", "Cocktail", "Cóctel"],
  ["Dessert", "Dessert", "Postre"],
  ["Welcome back", "Bon retour parmi nous", "Te damos la bienvenida de nuevo"],
  ["Sign in to access your personal space", "Connectez-vous pour accéder à votre espace personnel", "Inicia sesión para acceder a tu espacio personal"],
  ["Sign in →", "Se connecter →", "Iniciar sesión →"],
  ["Send me a magic link (passwordless)", "M’envoyer un lien de connexion (sans mot de passe)", "Enviarme un enlace mágico (sin contraseña)"],
  ["OR", "OU", "O"],
  ["Add Dish", "Ajouter un plat", "Añadir plato"],
  ["Add Event", "Ajouter une étape", "Añadir evento"],
  ["Add Hotel", "Ajouter un hôtel", "Añadir hotel"],
  ["Accompanied / +1", "Accompagné / +1", "Con acompañante / +1"],
  ["Dish Preference", "Préférence de plat", "Preferencia de plato"],
  ["Side", "Groupe", "Grupo"],
  ["Illustration (Image)", "Illustration (image)", "Ilustración (imagen)"],
  ["Custom music track created in AI Studio", "Musique personnalisée créée dans le Studio IA", "Música personalizada creada en el Estudio IA"],
  ["Pro Tip for Your Guests", "Conseil pour vos invités", "Consejo para tus invitados"],
  ["Reference Photos Links / URLs (Optional)", "Liens vers des photos de référence (facultatif)", "Enlaces de fotos de referencia (opcional)"],
  ["Venue Design Template (Replaces Map)", "Modèle du lieu (remplace la carte)", "Diseño del lugar (sustituye al mapa)"],
  ["Toggle sections on or off to customize what appears on your wedding invitation site.", "Activez ou désactivez les sections affichées sur le site de votre faire-part.", "Activa o desactiva las secciones que aparecen en el sitio de vuestra invitación."],
  ["No guests found. Click", "Aucun invité trouvé. Cliquez sur", "No se han encontrado invitados. Haz clic en"],
  ["to add one!", "pour en ajouter un !", "para añadir uno."],
  ["No guests assigned yet", "Aucun invité placé pour le moment", "Aún no hay invitados asignados"],
  ["Detailed list of all guest responses submitted via the web form.", "Liste détaillée de toutes les réponses envoyées depuis le formulaire en ligne.", "Lista detallada de todas las respuestas enviadas mediante el formulario web."],
  ["These are real-time responses submitted by your guests through your published online wedding invitation.", "Ces réponses sont envoyées en temps réel par vos invités depuis votre faire-part en ligne publié.", "Estas respuestas las envían vuestros invitados en tiempo real desde la invitación online publicada."],
  ["No submitted RSVPs found yet. Responses submitted by guests via your online invitation link will automatically appear here!", "Aucun RSVP reçu pour le moment. Les réponses envoyées par vos invités depuis votre faire-part en ligne apparaîtront automatiquement ici !", "Todavía no hay confirmaciones. Las respuestas enviadas desde vuestra invitación online aparecerán aquí automáticamente."],
  ["Organize your wedding tables and assign your confirmed guests.", "Organisez les tables de votre mariage et placez les invités ayant confirmé leur présence.", "Organiza las mesas de la boda y asigna a los invitados confirmados."],
  ["Share your online wedding invitation with your friends, family, and loved ones. Send your unique link or print your customized QR code for your physical invitations.", "Partagez votre faire-part en ligne avec vos proches. Envoyez votre lien unique ou imprimez votre QR code personnalisé sur vos invitations papier.", "Comparte vuestra invitación online con familiares y amigos. Envía el enlace único o imprime el código QR personalizado en las invitaciones físicas."],
  ["Copy and send this direct web address to your guests:", "Copiez et envoyez cette adresse à vos invités :", "Copia y envía esta dirección a tus invitados:"],
  ["Guests can scan this QR code with their mobile phone to open your wedding site instantly:", "Vos invités peuvent scanner ce QR code avec leur téléphone pour ouvrir instantanément votre site de mariage :", "Los invitados pueden escanear este código QR con el móvil para abrir al instante el sitio de vuestra boda:"],
  ["For questions about your invitation, revisions, or technical assistance, please contact our team by email.", "Pour toute question concernant votre faire-part, vos modifications ou un problème technique, contactez notre équipe par e-mail.", "Para cualquier consulta sobre la invitación, las revisiones o la asistencia técnica, escribe a nuestro equipo por correo electrónico."],
  ["Email Folde Wedding", "Écrire à FOLDÈ Wedding", "Escribir a FOLDÈ Wedding"],
  ["Elevate your invitation with custom artwork illustrations and bespoke background music for an unforgettable guest experience.", "Sublimez votre faire-part avec des illustrations personnalisées et une musique de fond sur mesure pour offrir une expérience inoubliable à vos invités.", "Realza vuestra invitación con ilustraciones personalizadas y música de fondo a medida para ofrecer una experiencia inolvidable."],
  ["Active custom elements on your website:", "Éléments personnalisés actifs sur votre site :", "Elementos personalizados activos en tu sitio:"],
  ["Set as Main Site Photo", "Définir comme photo principale du site", "Establecer como foto principal del sitio"],
  ["Set as Main Background Music", "Définir comme musique de fond principale", "Establecer como música de fondo principal"],
  ["Add to Site Photo Gallery", "Ajouter à la galerie du site", "Añadir a la galería del sitio"],
  ["Remove Illustration", "Retirer l’illustration", "Quitar ilustración"],
  ["Remove Music", "Retirer la musique", "Quitar música"],
  ["Live RSVP Response Sync", "Synchronisation des RSVP en direct", "Sincronización de confirmaciones en directo"],
  ["Our design studio has finalized your bespoke wedding invitation. You can now view it live and share your link with guests.", "Notre studio a finalisé votre faire-part de mariage sur mesure. Vous pouvez maintenant le consulter et partager le lien avec vos invités.", "Nuestro estudio ha finalizado vuestra invitación de boda a medida. Ya podéis verla y compartir el enlace."],
  ["Our Paris design studio is currently handcrafting your bespoke wedding invitation using all the details, photos, and preferences you provided.", "Notre studio parisien réalise actuellement votre faire-part sur mesure à partir de toutes les informations, photos et préférences transmises.", "Nuestro estudio de París está creando a mano vuestra invitación a medida con todos los datos, fotos y preferencias facilitados."],
  ["You will receive a notification email at", "Vous recevrez une notification à l’adresse", "Recibiréis una notificación en"],
  ["as soon as your custom website is published.", "dès que votre site personnalisé sera publié.", "en cuanto se publique vuestro sitio personalizado."],
  ["Your wedding website is now public and ready to be shared with your guests.", "Votre site de mariage est maintenant public et prêt à être partagé avec vos invités.", "Vuestro sitio de boda ya es público y está listo para compartirlo."],
  ["with our design team. Need adjustments to your text, photos, timeline, or color scheme? Submit your request below!", "avec notre équipe créative. Vous souhaitez modifier un texte, une photo, le programme ou les couleurs ? Envoyez votre demande ci-dessous !", "con nuestro equipo de diseño. ¿Necesitas ajustar textos, fotos, horarios o colores? Envía tu solicitud a continuación."],
  ["included in your package. Our team has finalized your design. If you require additional custom changes, reach out to us directly at", "inclus dans votre formule. Notre équipe a finalisé votre design. Pour toute modification supplémentaire sur mesure, contactez-nous directement à", "incluidas en tu plan. Nuestro equipo ha finalizado el diseño. Si necesitas cambios adicionales, escríbenos a"],
  ["Couples who customize their background music and photos several months in advance see the highest guest engagement and RSVP response rates.", "Les couples qui personnalisent leur musique et leurs photos plusieurs mois à l’avance obtiennent le meilleur engagement et davantage de réponses RSVP.", "Las parejas que personalizan la música y las fotos con varios meses de antelación logran una mayor participación y más confirmaciones."],
  ["Our Paris design studio has received all your details and your invitation site has been generated with your selections.", "Notre studio parisien a bien reçu toutes vos informations et le site de votre faire-part a été généré selon vos choix.", "Nuestro estudio de París ha recibido todos vuestros datos y ha generado el sitio de la invitación según vuestras selecciones."],
  ["Our team will review and validate within 3 business days", "Notre équipe effectuera la relecture et la validation sous 3 jours ouvrés", "Nuestro equipo revisará y validará el resultado en un plazo de 3 días laborables"],
  ["Our team will review, refine, and validate your custom invitation. You'll receive a notification email at", "Notre équipe va relire, affiner et valider votre faire-part personnalisé. Vous recevrez une notification à l’adresse", "Nuestro equipo revisará, perfeccionará y validará vuestra invitación. Recibiréis una notificación en"],
  ["when it's ready. You can also check the status from your studio space.", "dès qu’il sera prêt. Vous pourrez également suivre son avancement depuis votre espace studio.", "cuando esté lista. También podréis consultar su estado desde vuestro espacio de estudio."],
  ["Write your menu courses / details", "Décrivez les plats et les détails du menu", "Escribe los platos y detalles del menú"],
  ["Upload menu file (PDF, Image)", "Importer le menu (PDF ou image)", "Subir el menú (PDF o imagen)"],
  ["Upload photos you want us to include in your gallery (Max 10 photos)", "Importez les photos à intégrer à votre galerie (10 photos maximum)", "Sube las fotos que quieras incluir en la galería (máximo 10)"],
  ["Details / requests to add", "Détails et demandes à ajouter", "Datos y solicitudes que añadir"],
  ["Click to upload custom hero video (.mp4)", "Cliquez pour importer votre vidéo principale (.mp4)", "Haz clic para subir tu vídeo principal (.mp4)"],
  ["Click to upload envelope video (.mp4)", "Cliquez pour importer votre vidéo d’enveloppe (.mp4)", "Haz clic para subir el vídeo del sobre (.mp4)"],
  ["Partner 1 Name", "Prénom de la première personne", "Nombre de la primera persona"],
  ["Partner 2 Name", "Prénom de la seconde personne", "Nombre de la segunda persona"],
  ["Paste URL", "Coller l’URL", "Pegar URL"],
  ["Preview", "Aperçu", "Vista previa"],
  ["Reference 1", "Référence 1", "Referencia 1"],
  ["Reference 2", "Référence 2", "Referencia 2"],
  ["e.g. Table 4 - Colleagues", "ex. : table 4 – collègues", "p. ej., mesa 4 – compañeros"],
  ["e.g. March 30th, 2026", "ex. : 30 mars 2026", "p. ej., 30 de marzo de 2026"],
  ["Appetizers, main courses, desserts, dietary options...", "Entrées, plats, desserts, régimes alimentaires…", "Entrantes, platos principales, postres, opciones alimentarias…"],
  ["Share any Pinterest boards, Instagram posts, or websites you love...", "Partagez les tableaux Pinterest, publications Instagram ou sites qui vous inspirent…", "Comparte tableros de Pinterest, publicaciones de Instagram o sitios web que te inspiren…"],
  ["Tell us about your story, your wedding atmosphere, and the feeling you want guests to experience...", "Racontez-nous votre histoire, l’ambiance du mariage et l’émotion que vous souhaitez faire vivre à vos invités…", "Cuéntanos vuestra historia, el ambiente de la boda y lo que queréis que sientan los invitados…"],
  ["Examples: cinematic black-and-white photography, a wax seal, no pastel colours, editorial typography...", "Exemples : photos cinématographiques en noir et blanc, sceau de cire, aucune couleur pastel, typographie éditoriale…", "Ejemplos: fotografía cinematográfica en blanco y negro, sello de cera, sin colores pastel, tipografía editorial…"],
  ["Write down any text blocks, timeline events, or special layout requests you want us to add...", "Indiquez les textes, étapes du programme ou demandes de mise en page particulières à ajouter…", "Indica los textos, eventos del programa o solicitudes especiales de diseño que quieras añadir…"],
  ["Please select an envelope animation to continue.", "Veuillez sélectionner une animation d’enveloppe pour continuer.", "Selecciona una animación del sobre para continuar."],
  ["Please select a hero theme video to continue.", "Veuillez sélectionner une vidéo d’ambiance principale pour continuer.", "Selecciona un vídeo principal de ambiente para continuar."],
  ["Please enter both names to continue.", "Veuillez saisir les deux prénoms pour continuer.", "Introduce ambos nombres para continuar."],
  ["Please enter your email address.", "Veuillez saisir votre adresse e-mail.", "Introduce tu correo electrónico."],
  ["We could not save your details. Please try again.", "Nous n’avons pas pu enregistrer vos informations. Veuillez réessayer.", "No hemos podido guardar tus datos. Inténtalo de nuevo."],
  ["Please describe the modifications you would like to request.", "Veuillez décrire les modifications souhaitées.", "Describe los cambios que deseas solicitar."],
  ["You have reached the maximum of 2 revision rounds included in your plan.", "Vous avez utilisé les 2 cycles de modifications inclus dans votre formule.", "Has utilizado las 2 rondas de revisiones incluidas en tu plan."],
  ["Failed to send request. Please try again.", "La demande n’a pas pu être envoyée. Veuillez réessayer.", "No se ha podido enviar la solicitud. Inténtalo de nuevo."],
  ["An error occurred while signing in.", "Une erreur est survenue lors de la connexion.", "Se ha producido un error al iniciar sesión."],
  ["Please fill in all required fields.", "Veuillez remplir tous les champs obligatoires.", "Completa todos los campos obligatorios."],
  ["An error occurred during registration.", "Une erreur est survenue lors de l’inscription.", "Se ha producido un error durante el registro."],
  ["An unexpected error occurred.", "Une erreur inattendue est survenue.", "Se ha producido un error inesperado."],
  ["Google sign-in failed.", "La connexion avec Google a échoué.", "No se ha podido iniciar sesión con Google."],
  ["Please enter your email address first.", "Veuillez d’abord saisir votre adresse e-mail.", "Introduce primero tu correo electrónico."],
  ["Failed to send magic link.", "Le lien de connexion n’a pas pu être envoyé.", "No se ha podido enviar el enlace mágico."],
  ["Please select an image file.", "Veuillez sélectionner un fichier image.", "Selecciona un archivo de imagen."],
  ["Please choose an image smaller than 12 MB.", "Veuillez choisir une image de moins de 12 Mo.", "Elige una imagen de menos de 12 MB."],
  ["The image could not be uploaded. Please try again.", "L’image n’a pas pu être importée. Veuillez réessayer.", "No se ha podido subir la imagen. Inténtalo de nuevo."],
  ["Generation failed. Please try again.", "La génération a échoué. Veuillez réessayer.", "La generación ha fallado. Inténtalo de nuevo."],
  ["AI credits are included with Premium and Expert plans.", "Les crédits IA sont inclus dans les formules Premium et Expert.", "Los créditos IA están incluidos en los planes Premium y Expert."],
  ["Please enter a prompt or choose one of our suggestions.", "Saisissez une description ou choisissez l’une de nos suggestions.", "Escribe una descripción o elige una de nuestras sugerencias."],
  ["Network error. Please try again.", "Erreur réseau. Veuillez réessayer.", "Error de red. Inténtalo de nuevo."],
  ["Please enter or select a music style.", "Saisissez ou sélectionnez un style musical.", "Escribe o selecciona un estilo musical."],
  ["Unable to play this track. Please try again.", "Impossible de lire cette musique. Veuillez réessayer.", "No se puede reproducir esta pista. Inténtalo de nuevo."],
  ["Replay opening", "Rejouer l’ouverture", "Repetir la apertura"],
  ["Choose your package — full customization unlocks after payment", "Choisissez votre formule — la personnalisation complète se débloque après le paiement", "Elige tu plan: la personalización completa se desbloquea después del pago"],
  ["It is completely normal that you have not entered every detail yet. After payment, your private dashboard lets you customize all photos, videos, music, wording, RSVP settings, and event information.", "Il est tout à fait normal de ne pas avoir encore renseigné tous les détails. Après le paiement, votre tableau de bord privé vous permettra de personnaliser les photos, les vidéos, la musique, les textes, les réglages RSVP et toutes les informations de l’événement.", "Es totalmente normal que todavía no hayas introducido todos los datos. Después del pago, tu panel privado te permitirá personalizar las fotos, los vídeos, la música, los textos, los ajustes de confirmación y toda la información del evento."],
  ["Simple, one-time payment", "Paiement simple et unique", "Pago único y sencillo"],
  ["Choose how you want to create", "Choisissez votre niveau d’accompagnement", "Elige cómo quieres crearla"],
  ["Select the level of creative support that feels right for you. Every plan includes unlimited guests and RSVP management.", "Choisissez l’accompagnement créatif qui vous convient. Toutes les formules incluent les invités illimités et la gestion des RSVP.", "Elige el nivel de acompañamiento creativo que prefieras. Todos los planes incluyen invitados ilimitados y gestión de confirmaciones."],
  ["Complete everything after payment", "Complétez tout après le paiement", "Completa todo después del pago"],
  ["You do not need all your details yet. Your private dashboard unlocks photos, videos, music, wording, RSVP settings, and event information.", "Vous n’avez pas besoin d’avoir tous les détails maintenant. Votre tableau de bord privé débloque les photos, vidéos, musiques, textes, réglages RSVP et informations de l’événement.", "No necesitas tener todos los datos ahora. Tu panel privado desbloquea fotos, vídeos, música, textos, ajustes de confirmación e información del evento."],
  ["Most popular", "Le plus choisi", "El más elegido"],
  ["one-time", "paiement unique", "pago único"],
  ["Selected plan", "Formule sélectionnée", "Plan seleccionado"],
  ["Tap to view details", "Touchez pour voir les détails", "Toca para ver los detalles"],
  ["One-time payment · no subscription", "Paiement unique · sans abonnement", "Pago único · sin suscripción"],
];

const dictionaries = {
  fr: Object.fromEntries(rows.map(([en, french]) => [en, french])),
  es: Object.fromEntries(rows.map(([en, , spanish]) => [en, spanish])),
};

function translateDynamic(locale, value) {
  const replacements = locale === "fr" ? [
    [/^(\d+)\s*\/\s*2 Revisions Used$/, "$1 / 2 modifications utilisées"],
    [/^Requested Modifications \(Revision #(\d+) of 2\)$/, "Modifications demandées (demande n° $1 sur 2)"],
    [/^SUBMIT REVISION #(\d+) →$/, "ENVOYER LA DEMANDE N° $1 →"],
  ] : [
    [/^(\d+)\s*\/\s*2 Revisions Used$/, "$1 / 2 revisiones utilizadas"],
    [/^Requested Modifications \(Revision #(\d+) of 2\)$/, "Cambios solicitados (revisión n.º $1 de 2)"],
    [/^SUBMIT REVISION #(\d+) →$/, "ENVIAR REVISIÓN N.º $1 →"],
  ];
  return replacements.reduce((text, [pattern, replacement]) => text.replace(pattern, replacement), value);
}

export function interfaceText(locale, value) {
  if (!value || locale === "en" || !dictionaries[locale]) return value;
  const leading = value.match(/^\s*/)?.[0] || "";
  const trailing = value.match(/\s*$/)?.[0] || "";
  const core = value.trim().replace(/\s+/g, " ");
  const plain = core.replace(/^[✓✉️✨⏳🎨🎵🎶🌍🍽️👥💬📥📱🔍🔒🔗🖼️🗑🤍🪑↗️❌]+\s*/, "");
  const prefix = core.slice(0, core.length - plain.length);
  const translated = dictionaries[locale][core]
    || (plain !== core && dictionaries[locale][plain] ? `${prefix}${dictionaries[locale][plain]}` : null)
    || translateDynamic(locale, core);
  return `${leading}${translated}${trailing}`;
}

export default function LocalizedSurface({ locale = "en", children }) {
  const rootRef = useRef(null);

  useLayoutEffect(() => {
    if (locale === "en" || !rootRef.current) return undefined;
    const localizeNode = (node) => {
      if (node.nodeType === Node.TEXT_NODE) {
        if (!node.nodeValue?.trim() || ["SCRIPT", "STYLE", "TEXTAREA"].includes(node.parentElement?.tagName)) return;
        const next = interfaceText(locale, node.nodeValue);
        if (next !== node.nodeValue) node.nodeValue = next;
        return;
      }
      if (node.nodeType !== Node.ELEMENT_NODE || ["SCRIPT", "STYLE", "TEXTAREA"].includes(node.tagName)) return;
      ["placeholder", "title", "aria-label", "alt"].forEach((attribute) => {
        if (!node.hasAttribute(attribute)) return;
        const current = node.getAttribute(attribute);
        const next = interfaceText(locale, current);
        if (next !== current) node.setAttribute(attribute, next);
      });
      node.childNodes.forEach(localizeNode);
    };
    localizeNode(rootRef.current);
    const observer = new MutationObserver((mutations) => mutations.forEach((mutation) => {
      if (mutation.type === "characterData") localizeNode(mutation.target);
      mutation.addedNodes.forEach(localizeNode);
    }));
    observer.observe(rootRef.current, { childList: true, subtree: true, characterData: true });
    const animationFrame = requestAnimationFrame(() => localizeNode(rootRef.current));
    const refreshes = [250, 1000].map((delay) => setTimeout(() => localizeNode(rootRef.current), delay));
    return () => {
      observer.disconnect();
      cancelAnimationFrame(animationFrame);
      refreshes.forEach(clearTimeout);
    };
  }, [locale]);

  return <div ref={rootRef} lang={locale} style={{ display: "contents" }}>{children}</div>;
}
